### ISSUE TITLE
Broken links to Google documentation in your server Architecture document

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-server#1103]
## Describe the bug

Section "Overview" of your server architecture document lists links to the original documentation from Apple and Google.
However, the Google links are outdated / broken (error 404)

## Expected behaviour

The links should lead to documentation.

## Technical details

Document: https://github.com/corona-warn-app/cwa-server/blob/main/docs/ARCHITECTURE.md
Branch: main
Chapter: Overview
Link 1 and 4

- Host Machine OS (Windows/Linux/Mac):

**Comment by codejus** [comment]
Hi @ndegendogo 
It looks like this problem should be solved if #1082 gets merged. The current link to Google is also mentioned there

**Comment by ndegendogo** [comment]
@codejus thanks. 
I appreciate especially that you guys are adding an automatted check for broken links to your pipeline.

**Comment by codejus** [comment]
I'm not a dev :D
Just had the same problem as you a few days ago and found the PR when I was looking for somethin else.

**Comment by ndegendogo** [comment]
@codejus now is Christmas holidays so I find time to read through the documents
