### ISSUE TITLE
Outdated rate-limiting numbers for GAEN API calls documented in CWA-Server Distribution Service

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-server#1104]
## Describe the bug

Document "CWA-Server Distribution Service" 
https://github.com/corona-warn-app/cwa-server/blob/main/docs/DISTRIBUTION.md
section "Key Export" mentions that the GAEN API has rate-limiting.
However, the numbers given are outdated, at least for Apple with ENF v2.
See also [this comment](https://github.com/corona-warn-app/cwa-app-ios/issues/1631#issuecomment-750934463)
> there are only 6 checks every 24h allowed by Apple

and [this reference](https://github.com/corona-warn-app/cwa-app-ios/issues/1631#issuecomment-750941557)

## Expected behaviour
Correct numbers in the documentation. Ideally the new numbers are added and the old numbers retained, to ensure also interoperability with devices not (not yet) updated to the newest versions.
Please check also if the Android numbers are still up-to-date.

## Technical details
Document https://github.com/corona-warn-app/cwa-server/blob/main/docs/DISTRIBUTION.md
section "Key Export"

- Host Machine OS (Windows/Linux/Mac):

**Comment by mibrasap** [comment]
Hi @ndegendogo,
thanks for pointing this out. We decided to reference the official documents from Apple and Google to always reference the latest information.

Cheers
