### ISSUE TITLE
Support REST API for key distrubution on the test server

### ISSUE THREAD

**Issue by llewelld** [corona-warn-app/cwa-server#1217]
## Current Implementation

The current implementation of the test server generates a set of example distribution keys and allows them to be downloaded via the Zenko CloudServer S3-compliant object store.

## Suggested Enhancement

In practice, the real sever uses a REST interface rather than an S3 object store for downloading the diagnosis keys. This means clients that are built against the test server need adapting later to use the real API.

For example, the download server access to URLs such as `version/v1/diagnosis-keys/country/DE/date`, etc. should be supported.

## Expected Benefits

This would allow clients to be built and tested against the test server before being set to use the real servers, with a smooth and safe transition between the two.

It would have no effect on the non-test server implementation.

**Comment by roesslerj** [comment]
Hello llewelld,

as pointed out in my other comment, we have another setup internally that we use to test the clients against. A change such as suggested would increase the complexity of the test server without any real purpose or benefit for us.

Again, I want to thank you in the name of the team of the CWA for your interest and your effort.

Stay healthy!
Jeremias
