### ISSUE TITLE
Statistics documentation?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-server#1223]
## Your Question

Is there any documentation available which covers the role of the cwa-server in collecting, calculating and transmitting statistics to the CWA app?

I could not find this functionality mentioned in the [CWA-Server Architecture](https://github.com/corona-warn-app/cwa-server/blob/main/docs/ARCHITECTURE.md) document.

**Comment by hilmarf** [comment]
Dear @MikeMcC399,

the 'cwa-server' doesn't collect any nor calculates any statistics, but it reads in a json file coming from CWA-Analytics framework and transforms it into protobuf structure, which is then consumed by the mobile clients, when you open your app.

Unfortunately I don't have all the details where the CWA-Analytics framework gets its information from. But for sure its using the RKI as one of the data-sources.

I hope that answers your question.

Regards,
Hilmar

**Comment by MikeMcC399** [comment]
@hilmarf 

Thanks for your answer about the statistics! I don't believe there is any documentation on GitHub regarding the CWA-Analytics framework, which is a new term for me.

The FAQ article https://www.coronawarn.app/en/faq/#further_details refers to data from RKI and there was no question for me that the original infection numbers come directly from RKI. 

I was interested in the trend calculations and to be concrete, the 7-Day Incidence.

Does the trend for the 7-Day Incidence indicator come directly from the CWA-Analytics framework? Or does the CWA server keep historical data stored and calculate itself whether the value is trending upwards, staying steady or trending downwards. I would like to be able to point to lines of code to confirm that the 7-Day Incidence trend is based on comparing the value with the previous day and using a ±1% band for the determination of a steady trend (rather than comparing with the value one week previously and using a ±5% steady trend band).

**Comment by hilmarf** [comment]
Hi @MikeMcC399,

the cwa-server does not do any trend calculation. As mentioned, it's just reading json (e.g. [services/distribution/src/test/resources/stats](../tree/HEAD/services/distribution/src/test/resources/stats) and produces protobuf [common/protocols/src/main/proto/app/coronawarn/server/common/protocols/internal/stats](../tree/HEAD/common/protocols/src/main/proto/app/coronawarn/server/common/protocols/internal/stats). What the 'distribution' service does here is a 'mapping' of the trend-numbers from the json to the trend-enums in the protobuf.

No gathering of numbers, no real calculation.

Regards,
Hilmar

**Comment by MikeMcC399** [comment]
@hilmarf 
Thanks for the detailed confirmation of your previous statement!
