### ISSUE TITLE
When will the risk calculation change go live?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-server#1346]
## Your Question

* Source File: https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/main-config/v2/risk-calculation-parameters.yaml
* Line(s): 51 & 56
* Question: https://www.coronawarn.app/en/blog/2021-04-16-corona-warn-app-risk-calculation-further-improved/ says that the risk calculation has been changed so that encounters that are longer than 9 minutes are sufficient to issue a red warning. When will this change go live?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I can see corresponding changes from https://github.com/corona-warn-app/cwa-server/pull/1336 merged into https://github.com/corona-warn-app/cwa-server/tree/release/2.0.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Oh I See, the used file is https://github.com/corona-warn-app/cwa-server/blob/release/2.0/services/distribution/src/main/resources/main-config/v2/risk-calculation-parameters-1.15.yaml and not https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/main-config/v2/risk-calculation-parameters.yaml.

Thank you. Closing as answered.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

https://github.com/corona-warn-app/cwa-server/blob/6bdb56f55183d9d290acd2409e3895ce852f1ea5/services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/ApplicationConfigurationV2PublicationConfig.java#L65-L69

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks. So just that I get this right, versions lower than 1.15 will not get this risk calc change?
