### ISSUE TITLE
Consider signing index files

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#137]
## Current Implementation
Date, hour, country and version index files are plain, unsigned JSON arrays.

## Suggested Enhancement
Wrap index files in SignedPayloads.

## Expected Benefits
Attestation that there were no submissions during a time frame etc., basically because of the same reasons for which we sign the diagnosis keys themselves (proof of authenticity and validity, "undeniability").

**Comment by johanneseschrig** [comment]
Outdated

**Comment by pithumke** [comment]
I don't see how this issue is outdated. Which part of the Google/Apple spec prevents signing of indices?

**Comment by christian-kirschnick** [comment]
The ref implementation https://github.com/google/exposure-notifications-server shows how index files are used. We will keep to that approach, so we will not change the payload of the index file with signing information, which ensures compatibility for federation scenarios.

https://github.com/corona-warn-app/cwa-server/issues/203 is also changing the index files to the official approach, and hence the mentioned index files will not exist as is anymore. Still, signing the new-approach-index file still makes sense, but would need to be done with a different solution (e.g. transfer signature in header). We will track this once https://github.com/corona-warn-app/cwa-server/issues/203 is implemented.
