### ISSUE TITLE
Consider adding "/country/{{country}}" to submission endpoint

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#139]
## Current Implementation
Submission endpoint is `/version/{{version}}/diagnosis-keys`

## Suggested Enhancement
Change submission endpoint to `/version/{{version}}/diagnosis-keys/country/{{country}}`.

## Expected Benefits
At the moment we can not be 100% certain that we will never have to submit diagnosis keys to other countries. However, if we ever get that requirement, and needed to introduce a country differentiating parameter, this would be a breaking change and would force us to bump the overall API version. With the proposed change (and an initial implementation for only `/version/v1/diagnosis-keys/country/DE`), this issue can already be avoided. Also, the proposed change would align the submission and distribution APIs.

**Comment by christian-kirschnick** [comment]
This topic will be dealt with in the Federation/Roaming scenario. Current plan is to have a list of countries in the submission payload in order to indicate for which countries the keys are of interest.
