### ISSUE TITLE
Remove "empty" dates/hours from index files

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#140]
## Current Implementation
All dates/hours between the first submission and now (last full hour) are included in the index files, even if there were no submissions.

## Suggested Enhancement
Only list dates/hours for which there were submissions in the index files. The "empty" date/hour files should, however, still be generated, even if they are not in the index.

## Expected Benefits
Mobile clients need to do fewer requests (they can simply skip empty dates/hours).

**Comment by michael-burwig** [comment]
Why should the empty files still be generated?

**Comment by pithumke** [comment]
Basically to attest that there were really no submissions in that time window (and that the distribution run didn't just fail). Since we are not (yet) signing index files, I guess the best we can do is to just create and sign the empty exports.

**Comment by pithumke** [comment]
#436 removed empty dates/hours from the index but did not add the generation of empty export files.
