### ISSUE TITLE
Generated files for same chunk differ in binary

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#148]
After running the testdata profile twice, I noticed that the same file for the same chunk differs on byte level, although the file size is identical. This should not happen, as it will cause problems on CDN.

For the index file, it looks like missing sorting is causing the problem, one example:

`[23,18,21,22,19,20]`

**Comment by johanneseschrig** [comment]
Logic has changed, not relevant anymore

**Comment by pithumke** [comment]
How is this issue not relevant anymore? IMHO, generated files for the same chunk still shouldn't differ in binary.

**Comment by christian-kirschnick** [comment]
Since the generation code has changed a lot & Timon and me are working on  https://github.com/corona-warn-app/cwa-server/issues/203, we will have an eye on this as well. I will reopen this, in case https://github.com/corona-warn-app/cwa-server/issues/203 will not fix it.

**Comment by christian-kirschnick** [comment]
Re-opening, still valid.

**Comment by christian-kirschnick** [comment]
Changed to sorted list for the TEK Exports:
https://github.com/corona-warn-app/cwa-server/compare/issues/148-binary-diff

Then ran the assembly process twice and picked the 20 hour package for current day.

Unfortunately,
`colordiff -y <(xxd 20) <(xxd 20_2)`

Still shows some diffs.

**Comment by UnchartedBull** [comment]
Managed to convince the ZIP Library to create byte-identical archives. The payload signing creates different bytes for the same chunk each time though. Having the signing algorithm create the same bytes for the same chunk would be a security risk, so we can't create byte-identical archives for the same chunk.
