### ISSUE TITLE
Remove test certificate + private key

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#154]
## Current Implementation
Test/dev certificate and private key are checked in (see [here](https://github.com/corona-warn-app/cwa-server/tree/master/services/distribution/src/main/resources/certificates) and [here](https://github.com/corona-warn-app/cwa-server/tree/master/services/distribution/src/test/resources/certificates)).

## Suggested Enhancement
Remove Test certificate and private key.

## Expected Benefits
Checked in private key could cause misunderstandings and false-positives on security scans. Even when it's just a non-prod test/development key, we should not let any confusion/doubts arise regarding the security of this app.

@MKusber triage needed.

**Comment by christian-kirschnick** [comment]
@MKusber fixed by https://github.com/corona-warn-app/cwa-server/pull/185/files ?

**Comment by MKusber** [comment]
Fixed by #185
