### ISSUE TITLE
Why is `latest-ios` & `latest-android` same as `min-ios` & `min-android` in application.yaml

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-server#1600]
## Your Question
* Source File: https://github.com/corona-warn-app/cwa-server/blob/release/2.13/services/distribution/src/main/resources/application.yaml
* Line(s): https://github.com/corona-warn-app/cwa-server/blob/be5f3dd3c6e4df485c57a10054c4c136f2d4edf1/services/distribution/src/main/resources/application.yaml#L120-123
* Question: Why is `latest-ios` & `latest-android` same as `min-ios` & `min-android`? Shouldn't `latest-ios` & `latest-android` be the latest version released?

**Comment by Ein-Tim** [comment]
Hey @hilmarf,

just checking, maybe you know the answer to this question and could respond to it?

Ping @dsarkar

**Comment by mlenkeit** [comment]
@Ein-Tim both `latest-ios` and `latest-android` are not supported by CWA at the moment
