### ISSUE TITLE
Replace .env files to better secure devs

### ISSUE THREAD

**Issue by 1fabi0** [corona-warn-app/cwa-server#1611]
## Current Implementation
Currently there is an .env file in the repos with Configurations and secrets in it, which can be changed in Commits and pushed. 

## Suggested Enhancement
I would suggest to use a .env-template, which only templates the .env file. Also the .env file would be added to the .gitignore file. So new developers would have to copy the template ones and rename it to .env ones. 

## Expected Benefits
The benefit would be that devs can't accedently push their secrets to github and make them vulnerable.

**Comment by thomasaugsten** [comment]
This is overall a good idea we will consider this, but this env files are only for local development and will never include critical secrets-

**Comment by 1fabi0** [comment]
Even if it's closed I just want to point out, what I mean is, that a dev may accedently push a password e.g. the Postgres SQL password (maybe some dev has a hosted server or using for his local db a default password)
