### ISSUE TITLE
Misleading HTTP Status codes for incorrect paths and methods

### ISSUE THREAD

**Issue by bKiralyWdf** [corona-warn-app/cwa-server#165]
## Describe the bug

When calling invalid API paths the server responds with `500 Internal server error`.

## Expected behaviour

The server responds with a 400 family HTTP status code.

## Steps to reproduce the issue

```
$ curl -v <backend_url>/
[...]
< HTTP/1.1 500 
< Content-Type: text/html;charset=utf-8
< Content-Language: en
< Content-Length: 455
< Date: Mon, 18 May 2020 00:00:00 GMT
< Connection: close
< 
* Closing connection 0
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html>
```

## Technical details

- Host Machine OS (Windows/Linux/Mac): Ubuntu running Docker

**Comment by christian-kirschnick** [comment]
We are waiting for https://github.com/spring-projects/spring-security/pull/7052 to be available, which will be part of Spring Security 5.4.0. Current is 5.3.2.

**Comment by christian-kirschnick** [comment]
5.4 is currently In PRE phase.
![image](https://user-images.githubusercontent.com/64424068/85140619-ca047a00-b245-11ea-848f-d228570ebc0a.png)

**Comment by odrotbohm** [comment]
Given the fact that 5.4 is still a bit far out, I just reached out the Spring Security team to see whether they can do something about it in the 5.3 branch as well.

**Comment by odrotbohm** [comment]
Apparently there's a workaround for that [here](https://github.com/spring-projects/spring-security/issues/5007#issuecomment-369477840) until further resolution.

**Comment by hilmarf** [comment]
can't reproduce anymore...

```
curl -v https://submission.coronawarn.app/
< HTTP/1.1 403
...
< Date: Fri, 20 Nov 2020 13:52:51 GMT
```
