### ISSUE TITLE
Suggestion: Remove JndiLookup.class from log4j-core-2.*.jar until migrating away from log4j-core

### ISSUE THREAD

**Issue by hardfalcon** [corona-warn-app/cwa-server#1660]
First, I'm *not* a Java dev.

Still, I want to give two remarks/observations/suggestions about the whole log4j mess:
1. A library that tries to *parse* strings it was only supposed to *log*, and even has code that allows initiating outbound network connections *based on the results of that parsing*, is broken by design and probably shouldn't be used at all.
   An API that uses the same input vector to handle both potentially malicious input and to configure what the library actually does with the supplied potentially malicious input seems fundamentally unfit for purpose. IMO, this is comparable to patching together SQL query strings from unsanitized user input instead of just using prepared statements.
2. Until the migration away from this broken API is completed, it might be wise to preemptively, as a defense in depth measure, apply even to log4j versions >= 2.16.0 (explicitly including 2.17.0 and beyond) the mitigation method that upstream still [recommends](https://logging.apache.org/log4j/2.x/security.html#log4j-2.16.0) for users of log4j >= 2.0.0 < 2.16.0 who are unable to upgrade:
   ```
   zip -q -d log4j-core-*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class
   ```
   This simply deletes from the JAR file the class that actually performs the JNDI lookups. As far as I can tell, just like probably 99% of log4j users, you don't actually use log4j's JNDI "feature" at all, so the only "use case" for that class would actually be an attacker trying to execute malicious code after managing to find *yet another* way of circumventing upstream's patches to this fundamentally unsafe API.

**Comment by thomasaugsten** [comment]
Thanks for the recommendation the server is already running with log4j 2.17.0 with disabled JNDI

**Comment by dsarkar** [comment]
@hardfalcon Thanks for your suggestion and contributing to this porject. If you are happy with the answer above, please, close this issue. Of course, any further suggestions are welcome. Best wishes, DS


---
Corona-Warn-App Open Source Team
