### ISSUE TITLE
Implement final Google/Apple server API and file specifications

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#168]
## Current Implementation
Distribution and submission services implement our own API and file definitions.

## Suggested Enhancement
Implement final Google/Apple server API and file specifications, once a final version is available.

## Expected Benefits
- Being compliant to the "official" Google/Apple specs
- Potentially enabling "pan-european scenario"
- Remove file conversion from apps (by already outputting the files in the format expected by the Google/Apple client APIs).

**Comment by christian-kirschnick** [comment]
https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Exposure-Key-File-Format-and-Verification.pdf

**Comment by mh-** [comment]
If you consider replicating the Google reference implementation ("Google has created an [implementation of an EN server](https://github.com/google/exposure-notifications-server) that you can use as a reference"), which uses "Device Attestation", please also consider potential privacy impact of Device Attestation - see https://github.com/corona-warn-app/cwa-documentation/issues/62

**Comment by christian-kirschnick** [comment]
Hey @mh-,

although we fill try to stick to the proto definitions from Google/Apple as close as possible for the backend implementation, it does not necessarily mean we will process/send all fields in the protocol. There are a number of fields which are heavily debated within DPP (device attestation just being one of them), and DPP drives a lot of the implementation decisions in this project.

The backend topic for device attestation is tracked in https://github.com/corona-warn-app/cwa-server/issues/82.

cheers
Chris
