### ISSUE TITLE
Ensure correctness of date and hour indices

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#169]
## Describe the bug
App colleagues reported inconsistencies regarding what is and isn't included in date/hour index files.

## Expected behaviour
Implementation should comply to API specification.

## Additional info
Should be done after #168

**Comment by johanneseschrig** [comment]
Spec changed - not relevant anymore

**Comment by pithumke** [comment]
I don't see how this issue is not relevant anymore. Please quote which part of the Google/Apple spec makes a removal of the date/hour indices necessary.

**Comment by christian-kirschnick** [comment]
This ticket will be handled as part of https://github.com/corona-warn-app/cwa-server/issues/203. Index handling will be adjusted according to https://github.com/google/exposure-notifications-server. 

We will re-open in case app colleagues are reporting the same issue for the new index handling as well.
