### ISSUE TITLE
Need to append "/index" to all requests on local setup

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#176]
## Describe the bug
On the local setup (docker-compose), one needs to append `/index` to all GET requests.

## Expected behaviour
API as defined in the OpenAPI document.

## Technical details
This is a workaround to a ["fundamental design flaw"](https://github.com/minio/minio/issues/7335) in MinIO, through which files can not have the same name as directories. This is not an issue on "proper" S3 compatible storages (e.g. AWS or OpenShift) and only affects local development - on open shift, the files are properly renamed. However, this is still a deviation from the documented API.

## Possible Fix
**Option A**
- Remove MinIO and the "upload" distribution runner from the local setup, instead serve the files generated by the "assembly" runner from the local file system using something like nginx ([config from mock server can be reused](https://github.com/corona-warn-app/cwa-server/blob/6e7853c37c2a7a30bda104feefb50b29131335a5/tools/mock-server/nginx.conf)). This would enable easy end-2end scenario testing (submission to distribution), but would also mean that not all of our code is run locally.

**Option B:**
- Look for an alternative to MinIO that supports files and directories having the same name

**Option C:**
- Remove MinIO and force users to provide some S3 compatible bucket themselves (e.g. private AWS S3, etc.)

**Option D:**
- Add the "/index" suffixes to the actual API definition

**Option E:**
- Just leave this as is for now, wait for Apple/Google to finally release a backend API spec and then implement that instead. Any "fixing" of the current API probably needs to be thrown away in a few days anyways when they force an API spec onto us.

**Option F:**
- ???

**Comment by ole-lilienthal** [comment]
Will fix this together with #163 
This is WIP

**Comment by ole-lilienthal** [comment]
Cloudserver looks promising in that regards: https://s3-server.readthedocs.io/en/latest/GETTING_STARTED.html?highlight=path%20style#endpoints

**Comment by ole-lilienthal** [comment]
I was able to get the zenko/cloudserver running end-to-end with starting in a basic docker container setup but not as part of the docker-compose. Checkout the branch fix/cloudserver for the latest state. Here is what I tried:

Prerequisites:
* AWS CLI
* Postgres - docker or local - whatever works for you

## Docker based

* ```docker pull zenko/cloudserver```
* ```docker run --name s3server -p 8003:8000 -e REMOTE_MANAGEMENT_DISABLE=1 -e SCALITY_ACCESS_KEY_ID=accessKey1 -e SCALITY_SECRET_ACCESS_KEY=verySecretKey1 zenko/cloudserver```
* ```export AWS_ACCESS_KEY_ID=accessKey1```
* ```export AWS_SECRET_ACCESS_KEY=verySecretKey1```
* ```aws s3api create-bucket --bucket cwa --endpoint-url http://localhost:8003 --acl public-read```
* Check that objectstore is properly configured in distribution service. (port 8003)
* ```mvn install && cd services/distribution && mvn spring-boot:run -Dspring-boot.run.profiles=testdata```

Go ahead and download from http://localhost:8000/cwa/version/v1/diagnosis-keys/country/DE/date/2020-05-08/hour/18 

=> ✅

## Docker-compose based

* ```docker-compose pull objectstore```
* ```docker-compose run objectstore```
* Check that property in distribution service is set right. (port 8003)
* ```export AWS_ACCESS_KEY_ID=accessKey1```
* ```export AWS_SECRET_ACCESS_KEY=verySecretKey1```
* ```aws s3api create-bucket --bucket cwa --endpoint-url http://localhost:8003 --acl public-read``` => 💥 
* ```mvn install && cd services/distribution && mvn spring-boot:run -Dspring-boot.run.profiles=testdata``` => 💥 

@christian-kirschnick @pithumke

**Comment by CCFenner** [comment]
The `objectstore` endpoint needs to be defined in the `docker-compose.yml`, see  https://github.com/corona-warn-app/cwa-server/pull/228. This fixes the connection issue between was and cloudserver.

**Comment by ole-lilienthal** [comment]
Thanks @CCFenner 👍 
Saved my day... PR will follow in a bit, just some cleanup to be done.
