### ISSUE TITLE
Apple's Proposal for Exposure Key Validation

### ISSUE THREAD

**Issue by johanneseschrig** [corona-warn-app/cwa-server#179]
#92  Current Implementation

We used sensible assumptions for key validation.

## Suggested Enhancement

[Apple proposes](https://developer.apple.com/documentation/exposurenotification/setting_up_an_exposure_notification_server?changes=latest_beta): 

> An EN server must reject invalid key files uploaded from a client app. Uploaded key data is considered invalid if:
>
> Any ENIntervalNumber values from the same user are not unique
> 
> There are any gaps in the ENIntervalNumber values for a user
> 
> Any keys in the file have overlapping time windows
> 
> The period of time covered by the data file exceeds 14 days
> 
> The TEKRollingPeriod value is not 144
> 
> You may optionally want to validate the clock time the device submits.

## Expected Benefits

Adherence to reference implementations.

**Comment by johanneseschrig** [comment]
Part of https://github.com/corona-warn-app/cwa-server/issues/168

**Comment by michael-burwig** [comment]
In progress
- [ ] ENIntervalNumber values from the same user shall be unique.
- [ ] There must be no gaps for ENIntervalNumber values for a user.
- [ ] There must not be any keys in the file have overlapping time windows.
- [ ] The period of time covered by the data file must not exceed 14 days.
- [ ] The TEKRollingPeriod value shall be 144.
