### ISSUE TITLE
Failed to instantiate distribution service [release - cwa-server-2.19.0]

### ISSUE THREAD

**Issue by proywm** [corona-warn-app/cwa-server#1797]
I am building and deploying the CWA-server-2.19.0 using docker-compose. However, the distribution service fails with an exception.

Following is the error message:
## Describe the bug

distribution_1       | 2022-04-14T18:16:56+0000 INFO  main a.c.s.s.d.s.StatisticsToProtobufMapping[1]: [2020-07-09] Booster Vaccinated Card successfully created  
distribution_1       | 2022-04-14T18:16:56+0000 DEBUG main a.c.s.s.d.s.StatisticsToProtobufMapping[1]: The following statistics JSON entries were used to create the cards. Null values are omitted.  
distribution_1       | 2022-04-14T18:16:56+0000 DEBUG main a.c.s.s.d.s.StatisticsToProtobufMapping[1]: [2020-07-09] {"sevenDayRvaluePublishedDaily":0.83,"effective_date":"2020-07-09","update_timestamp":"2020-12-14T09:12:32,190","app_downloads_7days_avg":"112972.71428571429","app_downloads_7days_avg_growthrate":0,"app_downloads_7days_sum":790809,"app_downloads_7days_avg_trend_5percent":-1,"app_downloads_cumulated":15444142,"app_downloads_daily":67232,"infections_effective_7days_avg":357.7142857142857,"infections_effective_7days_avg_growthrate":0.8030788967286722,"infections_effective_7days_avg_trend_5percent":-1,"infections_effective_cumulated":198178,"infections_effective_daily":395,"labs_connected_cumulated":92,"labs_registered_cumulated":147,"persons_who_shared_keys_7days_avg_growthrate":0.5970149253731344,"persons_who_shared_keys_7days_sum":80,"persons_who_shared_keys_7days_avg_trend_5percent":-1,"persons_who_shared_keys_cumulated":288,"persons_who_shared_keys_daily":14,"persons_who_shared_keys_7days_avg":11.428571428571429,"seven_day_incidence_1st_reported_daily":598.1290138223786,"seven_day_incidence_1st_reported_growthrate":0.86,"seven_day_incidence_1st_reported_trend_1percent":1,"seven_day_r_value_1st_reported_daily":0.91,"seven_day_r_value_1st_reported_growthrate":0.9578947368421054,"seven_day_r_value_1st_reported_trend_1percent":-1,"seven_day_r_value_published_daily":0.83,"seven_day_r_value_published_growthrate":0.9651162790697674,"seven_day_r_value_published_trend_1percent":-1,"tests_total_daily":0,"administered_doses_daily":843978,"administered_doses_7days_avg":656704.8571428572,"administered_doses_cumulated":41517849,"administered_doses_7days_avg_growthrate":0.860829557981926,"administered_doses_7days_avg_trend_5percent":-1,"persons_with_first_dose_cumulated":31678786,"persons_with_first_dose_ratio":0.38100001215934753,"persons_fully_vaccinated_cumulated":9901626,"persons_fully_vaccinated_ratio":0.11900000274181366,"persons_with_third_dose_cumulated":56033026,"persons_with_third_dose_ratio":0.674,"seven_day_hospitalization_1st_reported_daily":168.5,"seven_day_hospitalization_1st_reported_growthrate":0.86,"seven_day_hospitalization_1st_reported_trend_1percent":1,"occupied_intensive_care_beds_reported_daily_ratio":0.11900000274181366,"occupied_intensive_care_beds_reported_daily_ratio_growthrate":0.86,"occupied_intensive_care_beds_reported_daily_ratio_trend_1percent":1}  
distribution_1       | 2022-04-14T18:16:56+0000 WARN  main o.s.c.a.AnnotationConfigApplicationContext[1]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appConfigurationV2StructureProvider' defined in URL [jar:file:/service.jar!/BOOT-INF/classes!/app/coronawarn/server/services/distribution/assembly/component/AppConfigurationV2StructureProvider.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createIosV2Configuration' defined in class path resource [app/coronawarn/server/services/distribution/assembly/appconfig/ApplicationConfigurationV2PublicationConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [app.coronawarn.server.common.protocols.internal.v2.ApplicationConfigurationIOS]: Factory method 'createIosV2Configuration' threw exception; nested exception is org.bouncycastle.util.encoders.DecoderException: exception decoding Hex string: invalid characters encountered in Hex string  
distribution_1       | 2022-04-14T18:16:56+0000 INFO  main c.z.h.HikariDataSource[1]: HikariPool-1 - Shutdown initiated...  
distribution_1       | 2022-04-14T18:16:56+0000 INFO  main c.z.h.HikariDataSource[1]: HikariPool-1 - Shutdown completed.  
distribution_1       | 2022-04-14T18:16:56+0000 INFO  main o.s.b.a.l.ConditionEvaluationReportLoggingListener[1]: \n\nError starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.  
distribution_1       | 2022-04-14T18:16:57+0000 ERROR main o.s.b.SpringApplication[1]: Application run failed org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appConfigurationV2StructureProvider' defined in URL [jar:file:/service.jar!/BOOT-INF/classes!/app/coronawarn/server/services/distribution/assembly/component/AppConfigurationV2StructureProvider.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createIosV2Configuration' defined in class path resource [app/coronawarn/server/services/distribution/assembly/appconfig/ApplicationConfigurationV2PublicationConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [app.coronawarn.server.common.protocols.internal.v2.ApplicationConfigurationIOS]: Factory method 'createIosV2Configuration' threw exception; nested exception is org.bouncycastle.util.encoders.DecoderException: exception decoding Hex string: invalid characters encountered in Hex string\u2028 at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)\u2028 at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)\u2028 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)\u2028 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)\u2028   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)\u2028  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)\u2028    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)\u2028 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\u2028      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) 
cwaserver2190_distribution_1 exited with code 1

## Steps to reproduce the issue

To reproduce the issue, docker-compose build and up from project root.

- Host Machine OS (Windows/Linux/Mac): Ubuntu

**Comment by ioangut** [comment]
Hello @proywm ! Can you please check if you can still reproduce this issue? It is happening on the latest release too? Can you also let me know which version of Ubuntu are you using ?

**Comment by hilmarf** [comment]
Closing this, since there was no response.
