### ISSUE TITLE
Should TAN's really allow SPACE characters?

### ISSUE THREAD

**Issue by MartinKolbSAP** [corona-warn-app/cwa-server#181]
* Source File:
https://github.com/corona-warn-app/cwa-server/blob/82d2ff55d604f122c7b003adce358979bc7bc7a2/services/submission/src/main/java/app/coronawarn/server/services/submission/verification/tan/TanAuthorization.java#L36
* Line(s): 36
* Question:
Should TAN's really consist of SPACE characters?

The RegEx for reading TANs is done with
```^(TAN|TELETAN) ([ a-zA-Z0-9]{6,30})$```

This means e.g. this is a valid TAN:
`TAN  ABCDEF`

There are **two consecutive SPACES** after "TAN". The first SPACE separating "TAN" and the actual content. The second SPACE is part of the "TAN value" (followed by the "ABCDEF" characters), meaning the value of the TAN is ` ABCDEF` (starting with SPACE).

This would also be a valid TAN (with `TAN TAN ANOTHER TAN` being the "value" of the TAN):
`TAN TAN TAN ANOTHER TAN`

**Comment by clouless** [comment]
Actually this means `TAN ABC DEF GGG 123` is valid tan, since the regex allows multiple whitespaces inside the 6 to 30 character group :) 

Should be 
```
Pattern.compile("^(TAN|TELETAN) ([a-zA-Z0-9]{6,30})$"); 
```

**Comment by johanneseschrig** [comment]
Hello together, 
thanks for the feedback! You are right, this should not be the regex for validating TANs. The reason for this code is that we are [still waiting for final specifications](https://github.com/corona-warn-app/cwa-server/pull/116#discussion_r426144634). We will change this code to something more sensible once we have that information available.

**Comment by christian-kirschnick** [comment]
TAN handling is not yet finalised, as @johanneseschrig wrote. We are currently discussing this internally and should have more clarity tomorrow. Therefore, let's just wait for the spec :)

By the way, the intention of the space character is to allow multiple words, as this is the use case for the Tele TAN scenario.

**Comment by clouless** [comment]
ok cool, @christian-kirschnick could you paste a link to the spec here once it is available? 
Will it be a markdown file in this repo? => https://github.com/corona-warn-app/cwa-documentation

**Comment by ole-lilienthal** [comment]
See https://github.com/corona-warn-app/cwa-server/pull/295
