### ISSUE TITLE
Use configuration classes instead of @Value annotations

### ISSUE THREAD

**Issue by TilmannF** [corona-warn-app/cwa-server#183]
You're using `@Value` about a dozen times, which isn't considered best practice anymore.

To quote Thomas Uhrig (@tuhrig):
> What will happen when you use this technique through your application? Well, whenever you need some property, you will inject it. You will inject it in services, controllers and components and you will properly inject the same property in different classes. That’s easy and absolutely what the mechanism is about.
> 
> However, this means nothing else than scattering your configuration about your whole application. Every class can pick a couple of properties to use. You will have no idea or control which class is using which properties. You will end-up with doing a full text search on your project to find out where a single key is used. You will have a lot of fun if you want to rename one of those keys or when you need to set each and every property for each and every class in your unit tests.
> [...]
> If you do so [use a configuration class], you will have a single point of responsibility to load and get your configuration from. As any other service, you can easily change the implementation. Maybe you don’t want to load your properties from a properties file, but from a database or web service!
([source](https://tuhrig.de/why-using-springs-value-annotation-is-bad/))

While this issue wouldn't qualify as high priority right now, it'll probably help in the future.

**Comment by MALPI** [comment]
Hey there,

I'd like to contribute and work on this issue?

BTW: Great that you uses the `good first issue` label.

**Comment by jwedel** [comment]
@MALPI You can have a look at the spring boot docs regarding the @ConfigurationProperties annotation:
- https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-enabling

The way to go would be to keep the property keys the same and use a separate class that binds the common key prefix (e.g. `services.submission`)  and provides type safe config values. Then inject that into the class that currently uses `@Value`.

See here for an example: 
- https://www.baeldung.com/configuration-properties-in-spring-boot

**Comment by indyaah** [comment]
@MALPI : Are you still planning to work on this? If you're not planning to I would be happy to take over.

**Comment by MALPI** [comment]
Hey,

I didn't find the time yet. Feel free to take it.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 21. Mai 2020, 03:52, Anuj Patel schrieb:

**Comment by pithumke** [comment]
I tried to use `@ConfigurationProperties` in an upcoming PR but didn't have any luck with it. I either ran into issues regarding default constructor visibility or the configuration property just didn't get autowired. Here's my attempt: https://github.com/corona-warn-app/cwa-server/commit/7d752e8ba17e41b20deb5c9299c14fe8539c9649. Unfortunately, I don't have the time right now to investigate this further, but I would be interested if somebody could please tell me what I was doing wrong.
