### ISSUE TITLE
Use constructor injection instead of field injection

### ISSUE THREAD

**Issue by TilmannF** [corona-warn-app/cwa-server#184]
Most of your dependency injection is done via field injection:
```
@Autowired
private CryptoProvider cryptoProvider;
```

Please consider constructor injection:
```
@Autowired
public SomeService(SomeOtherService someOtherService){
    this.someOtherService = someOtherService;
}
```

> [Constructor injection] is actually recommended over field injection, and has several advantages:
> the dependencies are clearly identified. There is no way to forget one when testing, or instantiating the object in any other circumstance (like creating the bean instance explicitly in a config class)
> the dependencies can be final, which helps with robustness and thread-safety
> you don't need reflection to set the dependencies. InjectMocks is still usable, but not necessary. You can just create mocks by yourself and inject them by simply calling the constructor
([source](https://stackoverflow.com/questions/40620000/spring-autowire-on-properties-vs-constructor))

Of course this isn't a critical issue, but it improves the code.

**Comment by flbaue** [comment]
I converted all the occurrences I could find. Please have a look and let me know if I missed something.

**Comment by jwedel** [comment]
@TilmannF @flbaue 
The `@Autowired` at the constructor is not required:

> If a bean has one constructor, you can omit the @Autowired

reference:
- https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/html/using-boot-spring-beans-and-dependency-injection.html#using-boot-spring-beans-and-dependency-injection
