### ISSUE TITLE
Use AssertJ instead of JUnit assertions

### ISSUE THREAD

**Issue by jwedel** [corona-warn-app/cwa-server#190]
## Current Implementation
Currently, standard JUnit assertions are use, e.g.:

```
assertEquals(BAD_REQUEST, actResponse.getStatusCode());
```

## Suggested Enhancement
Use [AssertJ](https://joel-costigliola.github.io/assertj/):
```
assertThat(actResponse.getStatusCode()).isEqualTo(BAD_REQUEST);
```

## Expected Benefits
- It is de-facto standard for spring boot tests
- It is already included in the `spring-boot-starter-test`
- It is easier to read due to its fluent API
- It is extensible for custom assertions
- It already offers powerful assertions for collections and more.

**Comment by SubOptimal** [comment]
Hi guys,

I'd like to contribute. May I pick this issue?

**Comment by indyaah** [comment]
@SubOptimal : First of all my apologies, I missed claiming before I started working on it. :(

Do you mind if I continue filing the PR?

**Comment by SubOptimal** [comment]
@indyaah I don't mind if you continue.

**Comment by christian-kirschnick** [comment]
Thanks for the fix @indyaah!
