### ISSUE TITLE
Missing Index on diagnosis_key.submission_timestamp

### ISSUE THREAD

**Issue by jwedel** [corona-warn-app/cwa-server#191]
*Disclaimer: I assume, since this application is not complete, there will change a couple of things and maybe this was already planned. This issues it at least meant as a reminder.*

## Current Implementation
The current Flyway migration script `db/migration/postgres/V1__createTables.sql` creates only the table `diagnosis_key` itself.

There are already two data base accesses to the column `submission_timestamp` in `DiagnosisKeyService`:

```
  public List<DiagnosisKey> getDiagnosisKeys() {
    return keyRepository.findAll(Sort.by(Sort.Direction.ASC, "submissionTimestamp"));
  }
```
and

```
  public void applyRetentionPolicy(int daysToRetain) {
    long threshold = LocalDateTime
        .ofInstant(Instant.now(), UTC)
        .minusDays(daysToRetain)
        .toEpochSecond(UTC) / 3600L;
    keyRepository.deleteBySubmissionTimestampIsLessThanEqual(threshold);
  }
``` 

## Suggested Enhancement
Depending on the expected number of entries in this table (I assume it will be *a lot*), this will result in very slow full table scans. There should be an index added to the column `submission_timestamp`.

## Expected Benefits
- Much faster data base access on high load and high number of db entries.

**Comment by michael-burwig** [comment]
Thank you, Jan!
Thanks for pointing out the missing column in the migration script.
I also agree that the index will most likely make sense here.

As for the anticipated performance gains wrt full table scans I am not 100% sure whether the planner would care much for the index.
See [Postgres Documentation - 11.4. Indexes and ORDER BY](https://www.postgresql.org/docs/12/indexes-ordering.html):
_...For a query that requires scanning a large fraction of the table, the explicit sort is likely to be faster because it requires less disk I/O due to a better-ordered access pattern. Indexes are more useful when only a few rows need be fetched..._

**Comment by jwedel** [comment]
Do you have any insights about the performance regarding that table now the system productive?

**Comment by christian-kirschnick** [comment]
@jwedel There are not many writes to the database table as of now. I guess it will take at least 2-3 weeks until a significant number of keys is actually stored there.

Just wondering whether sorting makes sense anyways - the current logic does not really care whether it's sorted or not, as it is going through each and every key anyways in order to determine the target package. Which only leaves the retention policy as a possible consumer.

**Comment by jwedel** [comment]
> Just wondering whether sorting makes sense anyways - the current logic does not really care whether it's sorted or not, as it is going through each and every key anyways in order to determine the target package. Which only leaves the retention policy as a possible consumer.

Yes, good point. But I think that `TestDataGeneration#getGeneratorStartTimestamp` assumes a sorted list and acceses it by index.

**Comment by christian-kirschnick** [comment]
Yeah, the `TestDataGeneration` class would need to be changed accordingly.


I just ran the retention for ~250k keys and I guess we should add the index:

```
2020-06-22T14:27:57+0200 INFO  main a.c.s.c.p.s.DiagnosisKeyService[74261]: Deleted 244717 diagnosis key(s) with a submission timestamp older than 14 day(s) ago. 
2020-06-22T14:32:45+0200 DEBUG main a.c.s.s.d.r.RetentionPolicy[74261]: Retention policy applied successfully. 
```

The first logging statement is misleading, as it is actually not reporting the end of the deletion task - so the actual deletion happens between both statements. That delete took 5 minutes on my machine, which is far too long.

**Comment by michael-burwig** [comment]
# Benchmark

## Setup
- MacBook Pro
- not optimized for consistent results
  - improvised setup
  - benchmark ran in the background while I was working

### 7dd1950bed279d6349acc1ce8bf01ad5810e67b7 - Instrumentation/Baseline
- remove index if it exists
- remove log statements
- add log statements for timing (insert, read, delete)
- set generation of test keys to fixed number and time frame (195139 keys)

### 5d9c9e338518f21b0508293f2562d9d693a880de - Index on submission_timestamp
- based on 7dd1950bed279d6349acc1ce8bf01ad5810e67b7
- create index on ``submission_timestamp`` column

### 5d6d497affb15a402b990890f74a75c45c7cbee1 - Native Query
- based on 7dd1950bed279d6349acc1ce8bf01ad5810e67b7
- replaces generated query with 2 native queries:
  - ``SELECT COUNT(*) FROM diagnosis_key WHERE submission_timestamp<=:threshold``
  - ``DELETE FROM diagnosis_key WHERE submission_timestamp<=:threshold``

## Execution
```
docker-compose build && docker-compose up distribution
# timed runs:
docker-compose up distribution && docker-compose up distribution && docker-compose up distribution
```

## Results
| Branch               | Write | Read | Delete |
| --------------- |:----:|:----:|:----:|
| Baseline            | 54 s | 5 s | 51 s |
|                           | 55 s | 5 s | 53 s |
|                           | 65 s | 5 s | 52 s |
| Index                 | 59 s | 5 s | 52 s |
|                           | 55 s | 5 s | 52 s |
|                           | 57 s | 5 s | 51 s |
| Native Queries | 55 s | 5 s | 145 ms |
|                           | 54 s | 5 s | 140 ms |
|                           | 54 s | 5 s | 141 ms |

[benchmark-base-line.log](https://github.com/corona-warn-app/cwa-server/files/4820632/benchmark-base-line.log)
[benchmark-with-index.log](https://github.com/corona-warn-app/cwa-server/files/4820636/benchmark-with-index.log)
[benchmark-native-without-index.log](https://github.com/corona-warn-app/cwa-server/files/4820634/benchmark-native-without-index.log)

## Interpretation
- index irrelevant
- generated delete query leads to ``n`` round trips
- that's ``n - 2`` round trips more than the native query 🤓

**Comment by jwedel** [comment]
Interesting. So neither delete nor select is using the index apparently. Maybe it just decided it’s faster to do a full table scan.

I would have assumed that the Spring Data generated query should do exactly the same. You’re custom query doesn’t to any magic...

I mean, the third option is really fast but I would actually try to understand why.

If you find the time, for the index, I would do an `explain analyze` and to check what the generated query does, I would enable spring data logging.

**Comment by stevesap** [comment]
Hi @jwedel thanks for the input. We discussed and as per @michael-burwig's analysis we do not see a benefit at this point. However, please feel free to conduct further analysis if you get the chance and open a new ticket in case you find otherwise.
