### ISSUE TITLE
min-android 1.5.1 differs from production 1.0.4 value

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-server#1962]
## Describe the bug

The `min-android` value served on 
https://svc90.main.px.t-online.de/version/v1/configuration/country/DE/app_config is 

`1.0.4` 

which differs from the value

`1.5.1`

stored in https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/application.yaml#L144

If CWA Android 1.4.0 is started, there is no prompt shown to the user that the app should be updated.

## Expected behaviour

The `min-android` value served on 
https://svc90.main.px.t-online.de/version/v1/configuration/country/DE/app_config should be the same as the value stored in https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/application.yaml#L144 which is currently `1.5.1`.

If `min-android` with the value of `1.5.1` were in production then starting CWA Android 1.4.0 should produce a prompt to update the app.

## Steps to reproduce the issue

1. In Android Studio check out CWA Android app release/1.4.x
2. Run CWA on Pixel 3a API 33 Android device emulator in Debug mode
3. Open Logcat in Android Studio and enter search term "UpdateChecker"

The log shows the following:

```
UpdateChecker           de.rki.coronawarnapp.dev             E  minVersionStringFromServer:1.0.4
UpdateChecker           de.rki.coronawarnapp.dev             E  Current app version:1.4.0
UpdateChecker           de.rki.coronawarnapp.dev             E  needs update:false
```

Alternatively install old released versions from https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/. As soon as a version < 1.0.4 is started, e.g. 1.0.0 or 1.0.2, a message "Update available" is output. 

![Update available](https://user-images.githubusercontent.com/66998419/202911146-6b74b2e4-7a8d-462d-8f19-6e10762719e2.jpg)

If version 1.0.4 is installed and started, no update message is output. This is consistent with min-Android being set to `1.0.4` in production.

## Technical details

- Android Studio Dolphin | 2021.3.1 Patch 1
- Pixel 3a API 33 Android device emulator
- CWA Android 1.4.0 (note that this version was not released. Version 1.5 followed version 1.3)

## Possible Fix

Clarify what the minimum enforced version of CWA Android in production is supposed to be and ensure alignment of https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/application.yaml with the values used in production.

**Comment by Ein-Tim** [comment]
- FYI: I opened https://github.com/corona-warn-app/cwa-server/issues/1963 asking the team to check for other differences between this repositories `main` branch & the production environment.

**Comment by MikeMcC399** [comment]
Also I would expect `min-android-version-code` /  `minVersionCode=48` and not `31` to be served.
