### ISSUE TITLE
Check for differences between `main` & production

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-server#1963]
@MikeMcC399 reported in https://github.com/corona-warn-app/cwa-server/issues/1962 that a value on production differs from this repositories `main` branch.
I reported an similar error in https://github.com/corona-warn-app/cwa-server/issues/1672.

Could you please make sure that the data on production is actually identical to the data in this repos `main` branch & if you find differences, fix them?

Thank you!

**Comment by MikeMcC399** [comment]
Is it reasonable to assume that the data on the production system is always in alignment to [main/resources/application.yaml](https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/application.yaml)?

That would be my understanding reading [main/docs/DISTRIBUTION.md](https://github.com/corona-warn-app/cwa-server/blob/main/docs/DISTRIBUTION.md) including 
- https://github.com/corona-warn-app/cwa-server/blob/main/docs/DISTRIBUTION.md#configuration 
- https://github.com/corona-warn-app/cwa-server/blob/main/docs/DISTRIBUTION.md#configuration-properties

**Comment by hilmarf** [comment]
Hi @Ein-Tim,
Hi @MikeMcC399,

to answer your question: "Is it reasonable to assume that the data on the production system is always in alignment to [main/resources/application.yaml](https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/application.yaml)?" 
I would clearly say: "No!"

Reason: the `application.yaml` contains a bunch of environment variables, which we can't always keep in sync or even don't want to publish - think of DB passwords, private keys and certificates - such sensitive information is stored in a [Vault](https://www.vaultproject.io/) instance, which is connected to the runtime environment at [OTC](https://github.com/corona-warn-app/cwa-faq/issues/325).

Nevertheless, we're sorry for the confusion (#1962). When we first made the change to minimum Android version requirements, we were facing a large discussion why we're excluding so many devices and had to very quickly revert those settings. Unfortunately the quickest way was to overwrite the environment variables via Vault, which we never played back into the sources. #1965 does this now.

:vulcan_salute: live long and prosper
Hilmar

**Comment by hilmarf** [comment]
@Ein-Tim - we'll check it once we're done with https://github.com/corona-warn-app/cwa-server/pull/1949 which needs currently our max attention.

Thanks for your patience.

**Comment by MikeMcC399** [comment]
@hilmarf 

> we'll check it once we're done with https://github.com/corona-warn-app/cwa-server/pull/1949 which needs currently our max attention.

- #1949 is now merged

**Comment by roesslerj** [comment]
@hilmarf is on a longer absent, so it will take a little longer until he can get back to this (talking approx. 4 weeks). I will see if I can do something meanwhile.

**Comment by Ein-Tim** [comment]
Is someone working on this issue? I'll not close it, as I consider it as transparency relevant that the production server and the `main` branch of this repository are in sync.

**Comment by GisoSchroederSAP** [comment]
All, 
as you already might have realized, we are moving directly into direction of maintenance and ramp-down of the CWA. 
This also implies that there will be no new major requirements from the customer, especially on the backend side. Thank you all for keeping an eye on our respositories being in sync; we are of course aware of that.
However, looking at current resources and timeline, we will most likely push these house-keeping activities into the last phase of CWA before the GitHub project is either closed or transferred/handed over. 
We currently see neither the need nor the ability to put effort into this synchronization in the short term.
Thanks for your understanding.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Okay, thank you very much for the information! I'll leave this issue open until the task has been performed (or one of the maintainers close it).

**Comment by hilmarf** [comment]
only 9 days left... closing this, due to lack of remaining resources

**Comment by Ein-Tim** [comment]
@hilmarf 

According to [the CWA website](https://www.coronawarn.app/en/) "CWA development ends on May 31, 2023". Isn't this a good task you could perform after the infrastructure shuts down on 01.05.2023, or are there also no resources for this, in my eyes very important and transparency relevant, in May?

**Comment by Ein-Tim** [comment]
See also https://www.coronawarn.app/en/faq/results/#ramp_down_github, which says: 
"Until May 31, 2023, the source code will be maintained as part of CWA development."

**Comment by hilmarf** [comment]
Hi @Ein-Tim, as you may have noticed. The mobile app states: "Es wird nur noch bis zum 30. April 2023 möglich sein, andere Personen ... zu warnen!"
That's why we'll turn the backend off as there is no reason to keep servers running #sustainability_responsibility.

Nevertheless, here are three excerpts from the [public](https://github.com/corona-warn-app/cwa-server/files/11351080/public.txt) (this) repository, the private [admin](https://github.com/corona-warn-app/cwa-server/files/11351089/admin.txt) repository (used for the helm-charts and deployments) and the secrets storage ([vault](https://github.com/corona-warn-app/cwa-server/files/11351098/vault.txt), which has highest priority in case variables are defined).
I've only quickly scanned through it and not found any differences to the public defaults... but maybe someone else has time and capacity to double check.

I hope this is satisfying and wish everyone a nice long weekend!
🖖 live long and prosper
Hilmar
