### ISSUE TITLE
Log diagnosis key validation failures in retrieval from DB

### ISSUE THREAD

**Issue by michael-burwig** [corona-warn-app/cwa-server#219]
## Current Implementation
Currently, ``DiagnosisKeyService.getDiagnosisKeys(...)`` filters out any invalid diagnosis keys from the query result silently.

## Suggested Enhancement
Log validation failures with a granularity in accordance with the required data protection/privacy standards.

## Expected Benefits
A validation failure after retrieval from the database indicates a data integrity issue and therefore should not go by unnoticed.

**Comment by jonaskoepper** [comment]
Hi,

I could start on a minimal implementation, that may 
1. Warn that there is a issue
1. Expose what constraints are violated

To log more details I would have to look up the relevancy of the content in more detail to make sure strict privacy protection is given.

If a smaller start is okay, I could provide code, for example at some point tomorrow.

Best
Jonas
