### ISSUE TITLE
teleTan format needs check digit

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-server#221]
## Feature description

The teleTan needs a check digit so that  typos can easily be verified.

## Problem and motivation

According to the solution architecture  document either an employee of a health authority or the hotline can give teleTans for entry by input field to the patient. The patient now enters the teleTan. Without some verification a patient can through a typo enter a valid but in his case wrong TeleTan. 

## Is this something you're interested in working on

No - I prefer document reviews

**Comment by christian-kirschnick** [comment]
Thanks for your valid concern. This topic will be covered by the mobile application. You should be able to check it out soon.
