### ISSUE TITLE
Change the type of "rolling start number" and "rolling period" on "diagnosis keys" to int.

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#233]
## Current Implementation
Currently, the type of the rolling start number and rolling period on diagnosis keys is `long`, see [here](https://github.com/corona-warn-app/cwa-server/blob/master/common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java#L59).

## Suggested Enhancement
Change both to `int`. Also consider renaming "rolling start number" to "rolling start interval number", as that was changed in the spec as well.

## Expected Benefits
Newest Apple/Google spec changed the rolling start interval number of temporary exposure keys to `int32` (see [here](https://developer.apple.com/documentation/exposurenotification/setting_up_an_exposure_notification_server)), which is `int` in Java. With the proposed change, we can avoid unnecessary type conversions.

**Comment by Akshatt** [comment]
Hi @pithumke is the issue assigned already? I'm new to open source and i would love to contribute!

**Comment by stevesap** [comment]
@Akshatt it's not assigned, please go ahead and assign yourself. Thanks for your contribution!

**Comment by jonaskoepper** [comment]
@stevesap It seems the repository permissions currently do not allow the collaborators to assign themself.

**Comment by Akshatt** [comment]
take

**Comment by stevesap** [comment]
@jonaskoepper thanks for heads up! looking into it ..

**Comment by Akshatt** [comment]
Hi @stevesap, I've forked and cloned the repo and have made changes where rolling start number and rolling period were defined. 
Should I also change `long` to `int` where they are passed as argument (See [here](https://github.com/corona-warn-app/cwa-server/blob/2af89a16b48d0e9bef0a5cda5db5a450e447f025/common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java#L75)) and returned (See [here](https://github.com/corona-warn-app/cwa-server/blob/2af89a16b48d0e9bef0a5cda5db5a450e447f025/common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java#L108) ) as well? 
Thanks for helping!

**Comment by stevesap** [comment]
@Akshatt yes that makes sense
