### ISSUE TITLE
S3 ObjectStore

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-server#234]
According to your [Documentation](https://github.com/corona-warn-app/cwa-server/blob/master/docs/architecture-overview.md) all, i quote,  "mobile app relevant files will be stored on the S3 Object Store". 

Furthermore I see an S3 Publisher and Distribution Runner as well [this comment](https://github.com/corona-warn-app/cwa-server/pull/145#issuecomment-629860391) asking on clarification.

**Question: Is any data hosted, stored or transfered through Amazon Inc. Infrastructure?**

**Comment by johanneseschrig** [comment]
Hello @TomTeeJay! Thank you for your question. 

As the comment you linked correctly states: the Object Store is hosted by Telekom in Germany. This Object Store's API is compatible with S3. 

**Answer: No data is hosted, stored or transferred through Amazon Inc. Infrastructure**.

**Comment by TomTeeJay** [comment]
copy, thank you vry much for clarification
