### ISSUE TITLE
Circle CI randomly fails on forked PRs

### ISSUE THREAD

**Issue by stevesap** [corona-warn-app/cwa-server#257]
Fails randomly and needs manual retrigger (sometimes several times)

There's no detailed error reported. Just 'Unauthorized'

![image](https://user-images.githubusercontent.com/5719743/82692032-39934380-9c5f-11ea-8273-d0ed554da254.png)

**Comment by stevesap** [comment]
Note this is NOT the same issue as #237

**Comment by jonaskoepper** [comment]
Example Pull Request showing the issue: https://app.circleci.com/pipelines/github/corona-warn-app/cwa-server?branch=pull%2F239

**Comment by CCFenner** [comment]
See https://status.circleci.com/incidents/ycdrk59mx2t3

**Comment by johanneseschrig** [comment]
Reason was circleci outage

**Comment by CCFenner** [comment]
But it look like it is not fixed yet: https://app.circleci.com/pipelines/github/corona-warn-app/cwa-server?branch=pull%2F215

**Comment by stevesap** [comment]
confirmed now - still an issue

**Comment by johanneseschrig** [comment]
Seems to be resolved.
