### ISSUE TITLE
Sonar - Remove public modifiers from jUnit5 tests

### ISSUE THREAD

**Issue by johanneseschrig** [corona-warn-app/cwa-server#268]
## Current Implementation
We have a public modifier on every test. this is not necessary. 

## Suggested Enhancement
Remove the modifier.

## Expected Benefits
Mitigates Code smells in [SonarCloud](https://sonarcloud.io/project/issues?id=corona-warn-app_cwa-server&resolved=false&severities=INFO&types=CODE_SMELL):

> JUnit5 is more tolerant regarding the visibilities of Test classes than JUnit4, which required everything to be public.
> In this context, JUnit5 test classes can have any visibility but private, however, it is recommended to use the default package visibility, which improves readability of code.

**Comment by felixbohnacker** [comment]
If possible, I would like to work on this.

**Comment by stevesap** [comment]
Thanks @felixbohnacker! We'll close this issue once we've verified in sonar that the code smell is resolved.

**Comment by felixbohnacker** [comment]
You're welcome. I tried to fix the remaining parts as well as I saw that there were still some open occurrences of this code smell in SonarCode.

**Comment by stevesap** [comment]
confirmed all relevant code smells are now resolved in sonar
