### ISSUE TITLE
Sonar - Code Brush up

### ISSUE THREAD

**Issue by johanneseschrig** [corona-warn-app/cwa-server#269]
There are some low hanging fruits in SonarCloud right now, which can be quickly fixed: 

- https://sonarcloud.io/project/issues?id=corona-warn-app_cwa-server&issues=AXI3CJw_vPFV4POpyUFe&open=AXI3CJw_vPFV4POpyUFe
- https://sonarcloud.io/project/issues?id=corona-warn-app_cwa-server&issues=AXI4Cmvdi9scHiKbJc85&open=AXI4Cmvdi9scHiKbJc85
- https://sonarcloud.io/project/issues?id=corona-warn-app_cwa-server&issues=AXI3CJtzvPFV4POpyUE7&open=AXI3CJtzvPFV4POpyUE7 and similar
- https://sonarcloud.io/project/issues?id=corona-warn-app_cwa-server&issues=AXI3CJwuvPFV4POpyUFX&open=AXI3CJwuvPFV4POpyUFX and similar
- https://sonarcloud.io/project/issues?id=corona-warn-app_cwa-server&issues=AXI3CJuavPFV4POpyUE-&open=AXI3CJuavPFV4POpyUE

See also https://github.com/corona-warn-app/cwa-server/issues/268

**Comment by vikram111** [comment]
Hi, I am new to open source and would love an opportunity to work on this issue.

**Comment by johanneseschrig** [comment]
Hi @vikram111! Sure, feel free to have a look at this, thanks!

**Comment by vikram111** [comment]
thanks @johanneseschrig  Can I please get write permissions as I am unable to push to the remote to make a pull request?

**Comment by christian-kirschnick** [comment]
Hey @vikram111, you can still create PR's when you forked this repo.

**Comment by johanneseschrig** [comment]
Hi @vikram111! Here is a guide on the steps to create a PR from a fork: https://guides.github.com/activities/forking/ 

Thanks!

**Comment by vikram111** [comment]
thanks a lot for your help @johanneseschrig, really appreciate it. I have raised a pull request for this now : https://github.com/corona-warn-app/cwa-server/pull/274
