### ISSUE TITLE
Sonar - Exception handling

### ISSUE THREAD

**Issue by johanneseschrig** [corona-warn-app/cwa-server#270]
SonarCloud is [currently complaining](https://sonarcloud.io/project/issues?id=corona-warn-app_cwa-server&resolved=false&severities=MAJOR) about exception handling in many places. We need to mitigate/audit these issues.

**Comment by elch78** [comment]
Fixed the "dont log and throw" issues.

In my projects I normally disable this rule: "Define and throw a dedicated exception instead of using a generic one." As long as there's no way to handle the exception separately it's totally fine to throw RuntimeException.

**Comment by stevesap** [comment]
The remaining instances of 'Define and throw a dedicated exception instead of using a generic one' have been marked as wontfix in sonar where no less-generic alternative to RuntimeException was found to be suitable.
