### ISSUE TITLE
use org.springframework.transaction.annotation.Transactional in DiagnosisKeyRepository.java

### ISSUE THREAD

**Issue by AndresFelipeRG** [corona-warn-app/cwa-server#273]
## Current Implementation

 @ Transactional annotation in DiagnosisKeyRepository.java

## Suggested Enhancement

When developing a Spring application it's recommended to use the annotation org.springframework.transaction.annotation.Transactional instead of the annotation @ Transactional from javax.transaction.Transactional.

## Expected Benefits
Importing org.springframework.transaction.annotation.Transactional is a better practice and offers more options

**Comment by elch78** [comment]
No need for @Transactional at all. https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#transactions

> By default, CRUD methods on repository instances are transactional. For read operations, the 
transaction configuration readOnly flag is set to true. All others are configured with a plain @Transactional so that default transaction configuration applies.

**Comment by odrotbohm** [comment]
I don't think `DiagnosisKeyRepository` needs any changes right now. `@Transactional` on a repository usually only makes sense with a `readOnly = true` on query methods that return large data sets.

Regarding the debate between the JavaEE and Spring specific annotation, there's also no need for change for the sake of change. I think the most important aspect here is to be consistent across classes. The Spring annotation indeed allows a few additional knows to be tweaked. But unless you actually need those – and I think the transaction requirements for this app are not that extraordinary – both are just fine.
