### ISSUE TITLE
Add DB Index 

### ISSUE THREAD

**Issue by AndresFelipeRG** [corona-warn-app/cwa-server#275]
## Current Implementation
Flyway PostGreSQL script

## Suggested Enhancement
Under the db/migration/postgres folder add a SQL script, using the CREATE INDEX command, to create a DB Index.

## Expected Benefits
Indexes are primarily used to enhance database performance

**Comment by jwedel** [comment]
@AndresFelipeRG Is this a duplicate of #191?
