### ISSUE TITLE
Maven identifiers

### ISSUE THREAD

**Issue by jhagestedt** [corona-warn-app/cwa-server#287]
Are the maven identifiers like groupId, artifactId and name correct?

https://github.com/corona-warn-app/cwa-server/blob/3f860372478e656f29ef81d2c690f28dd12501c0/pom.xml#L11-L14

As the official domain is https://coronawarn.app wouldn't groupId `app.coronawarn`, artifactId `cwa-server` and name `cwa-server` like repository name be better?

In sonarcloud there is just `server` displayed - `cwa-server` would match more precise or?
https://sonarcloud.io/dashboard?id=corona-warn-app_cwa-server

**Comment by CCFenner** [comment]
There was a discussion about `app.coronawarn` in https://github.com/corona-warn-app/cwa-server/pull/29. 
I think this should be aligned with the over services, e.g. [corona-warn-app/cwa-verification-server](https://github.com/corona-warn-app/cwa-verification-server) [uses](https://github.com/corona-warn-app/cwa-verification-server/blob/master/pom.xml#L6) `app.coronawarn.verification` as groupId.

Sonar is picking up the `<name>` and `<description>`, but that can be controlled with `sonar.projectName` and `sonar.projectDescription`.

**Comment by zhedar** [comment]
The repository is named cwa-server, so the artifact id `cwa-server` might be better suited than just plain `server`. As `org.opencwa` is also registered, it probably is an acceptable group id. I personally like `app.coronowarn` better, but that's just personal taste in the end.

As @CCFenner pointed out, at least the same domain (top & 2nd level) should be used throughout the different repos. So either use `app.coronowarn` or `org.opencwa` everywhere as a group id.

**Comment by johanneseschrig** [comment]
Hello together, thanks for the question and the input! 

There have been considerations to keep these identifiers consistent with the other code bases, like the app clients, and the topic is still ongoing. However, as stakeholders like our current deployment process somewhat depend on this, we want to wait for a final decision until we proceed with any changes. So for now, we will keep this groupId, but it may be changed in the future.
