### ISSUE TITLE
Ensure uniqueness of diagnosis keys

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#289]
## Current Implementation
The uniqueness of diagnosis keys is neither guaranteed by the database, nor by validation logic.

## Suggested Enhancement
Ensure that diagnosis keys in the database are unique (there are no duplicates).

What needs to be decided:
- [x] Is it sufficient to guarantee the uniqueness of the diagnosis key or should the uniqueness of diagnosis key + submission timestamp (+maybe even more fields) be guaranteed?
- [x] Should the duplicate check happen on the database (`UNIQUE` constraint) or in the server logic (e.g. during the validation of submitted keys)?
- [x] If the check happens on the database: Should the `id` column be removed and replaced with the diagnosis key (+submission timestamp) as (composite) primary key?
- [x] How should the server react when a duplicate diagnosis key is submitted (update, error, etc.)?

**Edit:** Decisions are below.

**Comment by pithumke** [comment]
Decisions made:
- Ensuring the uniqueness of the diagnosis key is sufficient
- Duplicate check should happen on the database
- `id` column should be removed
- `key_data` column should become primary key
- If we encounter problems with the current type (`bytea`) of `key_data` as primary key, then change the type to a base64 encoded String
- When duplicate keys are submitted, the server should just ignore them (no update, no error).

**Comment by oiime** [comment]
@pithumke Was referenced back to here from a different issue, What would be the value of base64 encoding the UUID? it'll just take up even more space than even using char(32). there is a UUID type already in pg that'll give better seek performance and cost 16 bytes per entry instead of 32

About the risk of collision itself, with UUIDv4 that is quite unlikely even with billions of records, However if you don't want to suffer the occasional exception on the server side you can just add `ON CONFLICT DO NOTHING` to swallow the error

**Comment by pithumke** [comment]
Hi @oiime, thank you for the remarks! Good point with the UUID type, I'll bring it up in the team discussions and report back. However, please note that, to my knowledge, the type of the diagnosis keys is not explicitly stated as UUID by the Google/Apple spec, but only as "Data" (see [here](https://developer.apple.com/documentation/exposurenotification/entemporaryexposurekey/3583679-keydata)) containing 16 bytes (see [here](https://www.blog.google/documents/60/Exposure_Notification_-_Cryptography_Specification_v1.1.pdf)). This can, in theory, be mapped to a UUID, but I would like to investigate if the PG UUID type implies any restrictions. For example, UUIDv4 reserves 6 of the 128 bits for version information, leaving only 122 bits for the payload - and this would cause major problems for us.

Regarding the collisions: we currently also don't see this as a major risk. Our current strategy, as you proposed, is to simply ignore duplicates.

**Comment by oiime** [comment]
@pithumke Well, you're the one defining both the client and the server side, the EN API is agnostic to its content to allow that freedom of implementation, so you can define that key to be whatever you want it to be, currently you are validating it as UUID in the server and the test case generates a UUIDv4. the UUID data type follows RFC 4122 as you would expect and would naturally cover UUIDv4. All UUID versions reserve a place for version information. _please_ do not try to come up with your own UUID variant if that is what is suggested here

**Comment by pithumke** [comment]
Hi @oiime, thank you for your comment.

> Well, you're the one defining both the client and the server side, the EN API is agnostic to its content to allow that freedom of implementation, so you can define that key to be whatever you want it to be

Yes, we do specify and develop both the CWA server and client. However, we neither specify nor develop the on-device APIs - that is done by Apple and Google. Inside those on-device APIs is where the keys are being generated and that does not give us much freedom regarding data types on our end. In the specification it is stated, that the key data consists of 16 bytes (= 128 bits). Since the use of UUID would restrict that to 122 bits, we can not use it as the column type on postgres.

> currently you are validating it as UUID in the server and the test case generates a UUIDv4

I am not aware of any UUID handling in our current code base, besides for TANs (which are not stored on the server). Can you please link which specific code you are referring to?

> please do not try to come up with your own UUID variant if that is what is suggested here

I didn't mean to suggest that and we don't want to come up with an own UUID variant. This is why we decided to go for a base64 encoded string for now (if bytea turns out to cause problems).

**Comment by oiime** [comment]
@pithumke 

> However, we neither specify nor develop the on-device API

I guess I rely on looking at the API itself, perhaps apple or google or both have a specific implementation they mandate or suggest, if that is the case then using UUID is wrong anyway 

> I am not aware of any UUID handling in our current code base, besides for TANs

I am likely conflating the two, I have only skimmed through the code and what I recalled was the test generating UUIDv4

> I didn't mean to suggest that and we don't want to come up with an own UUID variant. This is why we decided to go for a base64 encoded string for now (if bytea turns out to cause problems).

base64 seems like an unnecessary step that'll just take up more space and computation, you do it to avoid just storing it in a char(16) as-is? though I don't see why bytea wouldn't work as a PK, especially as you'd never update it

**Comment by alvar-freude** [comment]
The postgreSQL UUID data type stores 128 bits of data and it is up to the user how to use them. So, the UUIDs provided by the API from Apple/Google fit into an UUID field without problems and without bytea conversion. I like bytea, but the conversion is a little bit tricky. 

And UUID has two more advantages: bytea needs a length indicator (4 bytes) und requires, that each row/tuple has variable length, which makes some queries slower. Usually it is good practice, to avoid variable length columns or put them to the end of all columns (which would look weird here).

See [documentation for UUID Type](https://www.postgresql.org/docs/current/datatype-uuid.html) (and #451).
