### ISSUE TITLE
Maven build failing with POM parsing error

### ISSUE THREAD

**Issue by StevenArzt** [corona-warn-app/cwa-server#297]
## Describe the bug

When trying to build the server using maven, the build fails because the POM file cannot be parsed:

```
[ERROR] 'dependencies.dependency.version' for org.opencwa:protocols:jar must be a valid version but is '${revision}'. @ line 30, column 16
[ERROR] 'dependencies.dependency.version' for org.opencwa:persistence:jar must be a valid version but is '${revision}'. @ line 38, column 16
[ERROR] 'dependencies.dependency.version' for org.opencwa:protocols:jar must be a valid version but is '${revision}'. @ line 43, column 16
```

## Steps to reproduce the issue

``mvn package`` should run smoothly.

## Technical details

Problem found on a Jenkins CI machine on Linux. The same configuration worked just fine a week ago, we simply hit the "Build" button on the very same unmodified project.

## Possible Fix

Introduce / fix the missing ``revision`` variable.

**Comment by johanneseschrig** [comment]
Hi Steven! Thank you for raising this with us. Which maven version is running on your jenkins?

**Comment by StevenArzt** [comment]
It's version ``3.6.3``

**Comment by stevesap** [comment]
The `revision` variable is located in the [maven.config](https://github.com/corona-warn-app/cwa-server/blob/master/.mvn/maven.config)

**Comment by StevenArzt** [comment]
That option is not being picked up. I manually changed the Maven options in the Jenkins project configuration options to include ``-Drevision=0.4.1-SNAPSHOT`` and can now build the server.

**Comment by johanneseschrig** [comment]
Running locally, it seems to be picked up for me. Did you try `mvn package` locally?

**Comment by StevenArzt** [comment]
Local build on Windows works. I also tested locally on the build machine, and that also seems to work. I have no idea why the build messes up in Jenkins. Thanks for the assistance.
