### ISSUE TITLE
CryptoProvider is not checking resources on startup

### ISSUE THREAD

**Issue by elch78** [corona-warn-app/cwa-server#306]
## Current Implementation
Resource are loaded in the getPrivateKey and getCertificate methods. If the resources can't be loaded an exception is thrown at runtime. 

Also the UnitTest CryptoProviderTest is not testing what the name 'constructorInitializesCryptoArtifacts' suggests. 

## Suggested Enhancement
Load the resources in a @PostConstruct method. If resources can't be loaded an exception is thrown at startup and the application will not start.

## Expected Benefits
Configuration errors are detected on startup not during runtime. If the application is deployed in a blue/green fashion the error can be fixed before the user is affected.

**Comment by WilliamLin** [comment]
Hi, I am new to the open-source project, but I would like to start making the contribution. This task seems simple enough for a beginner. Please assign this task to me, or any other low hanging fruit.  Thanks
