### ISSUE TITLE
Retention: Enforce period on Object Store

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#329]
Currently, the retention period is only enforced for keys on the database, but it should be enforced on the S3 as well.

Therefore, we need to delete the items on the S3, when the retention policy is reached.

When the retention mechanism is kicked off, and then delete the following keys with the prefix:
`version/v1/diagnosis-keys/country/DE/date/<RETENTIONDATE>`
Where RETENTIONDATE is `current date - retention period`.

Ideally, we should also try to delete older items as well, in case the retention run did not succeed or did not run at all.

**Comment by pithumke** [comment]
I propose to just remove the "delta upload" feature from the S3Publisher (see [here](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/S3Publisher.java#L75)) and instead just wipe the whole bucket on every distribution run and to upload everything anew. This way, the only place where retention policies need to be applied is the DB as a single source of truth (which is already done) and we remove some moving parts and complexity that could potentially cause problems. Also see review comment [here](https://github.com/corona-warn-app/cwa-server/pull/147#discussion_r426311639).
