### ISSUE TITLE
Missing test results and code coverage in SonarCloud

### ISSUE THREAD

**Issue by CCFenner** [corona-warn-app/cwa-server#334]
As the sonar goal is executed with skip tests not results are available. Prior to https://github.com/corona-warn-app/cwa-server/pull/332 results from previous package were used. 
Due to this sonar currently has no information about executed tests and code coverage. 

/FYI @ole-lilienthal

**Comment by johanneseschrig** [comment]
Change was reverted - test coverage is back.
