### ISSUE TITLE
Blank URL in RiskScoreClassificationValidator

### ISSUE THREAD

**Issue by phros** [corona-warn-app/cwa-server#341]
In `app.coronawarn.server.services.distribution.assembly.appconfig.validation.RiskScoreClassificationValidator#validateUrl` [(link to source code)](https://github.com/corona-warn-app/cwa-server/blob/63dda0c2a5e1ff09fe998dd05637d76dea2e3833/services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/validation/RiskScoreClassificationValidator.java#L89) an empty URL does not lead to an error. This is not in line with e.g. validation of a label. In case the label is blank, an error is added. Maybe you can check that this is implemented as intended.

**Comment by stevesap** [comment]
Confirmed URL should **not** be empty - It should be a valid URL with http/https as allowed protocol
