### ISSUE TITLE
Potential Path traversal

### ISSUE THREAD

**Issue by phros** [corona-warn-app/cwa-server#343]
In `app.coronawarn.server.services.distribution.assembly.io.IO#makeNewFile` [(link to source)](https://github.com/corona-warn-app/cwa-server/blob/63dda0c2a5e1ff09fe998dd05637d76dea2e3833/services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/io/IO.java#L41), the method takes a root path and a file name for creating a new file. In case the filename can be chosen arbitrarily by a user/attacker, the implementation is prone to path traversal attacks. 

To avoid this, the given name needs to be sanitized or filtered.

**Comment by stevesap** [comment]
Thanks for the input. At this point, we are confident there is no user input involved in directory creation. However, we would welcome any contribution to include whitelisting of paths provided.

**Comment by johanneseschrig** [comment]
The filename cannot be chosen arbitrarily by a user/attacker.
