### ISSUE TITLE
OpenAPI 3 specification using Swagger UI?

### ISSUE THREAD

**Issue by espiegelberg** [corona-warn-app/cwa-server#348]
I see that the distribution and submission services each contain an api_v1.json file containing openapi documentation.

I propose the addition of openapi and Swagger UI to have the project automatically generate the OpenAPI 3 specification docs and making them available for live discovery. Documentation and a general introduction of what I propose can be found from https://www.baeldung.com/spring-rest-openapi-documentation.

Should this be something the project leadership is interested in having contributed, I have both the interest and bandwidth available to prepare a PR. Please let me know if this is something the group would like me to pursue.

**Comment by stevesap** [comment]
Thanks for the input and your offer to support. At this point, we decided to stick to the manually maintained [submission service api_v1.json](https://github.com/corona-warn-app/cwa-server/raw/master/services/submission/api_v1.json) and [distribution service api_v1.json](https://github.com/corona-warn-app/cwa-server/raw/master/services/distribution/api_v1.json).

Interested consumers can easily import these into [Postman](https://www.postman.com/) or into [Swagger Editor](https://editor.swagger.io/) for easier consumption.

Related: https://github.com/corona-warn-app/cwa-server/issues/372
