### ISSUE TITLE
Use @Data in DistributionServiceConfig.java

### ISSUE THREAD

**Issue by AndresFelipeRG** [corona-warn-app/cwa-server#353]
## Current Implementation
DistributionServiceConfig class
## Suggested Enhancement
Use @Data annotation. @Data is a convenient shortcut annotation that bundles the features of @ToString, @EqualsAndHashCode, @Getter / @Setter and @RequiredArgsConstructor 
## Expected Benefits

- Reduce boilerplate code
- Don't need to test setters and getters

**Comment by zhedar** [comment]
Note: This probably needs a discussion, if Lombok should be used – like it currently already is in https://github.com/corona-warn-app/cwa-verification-server.

This would then need Lombok to be installed as a Java-Agent in a comitter's IDE and probably needs to be documented in the prerequisites as well.

**Comment by stevesap** [comment]
Thanks for the suggestion. For the time being we are not going ahead with Lombok. However, we may consider it down the road and reopen this.
