### ISSUE TITLE
Use license-maven-plugin to ensure file headers and third party license file generation

### ISSUE THREAD

**Issue by johanneseschrig** [corona-warn-app/cwa-server#354]
## Feature description

We should consider the use of [license-maven-plugin](https://www.mojohaus.org/license-maven-plugin/)

## Problem and motivation

Currently, adding a license header is a manual task, as well as updating the third party license file. This should optimally be automated.

**Comment by stevesap** [comment]
[license-maven-plugin](https://www.mojohaus.org/license-maven-plugin/) was integrated in https://github.com/corona-warn-app/cwa-server/pull/362 for updating file license headers via manual command `mvn license:update-file-header`

Remaining tasks on this issue:
1. Generate the [THIRD-PARTY-LICENSE](https://github.com/corona-warn-app/cwa-server/blob/master/THIRD-PARTY-NOTICES) file
2. Automate the maven plugin execution

**Comment by CCFenner** [comment]
I was able to generate a `THIRD-PARTY-NOTICE` file with the `license-maven-plugin`. However this only contains the dependencies (maven-GAV, url, name) and not the actual license text. Would this already be sufficient?

**Comment by stevesap** [comment]
@tkowark can you please advise if such a generated `THIRD-PARTY-LICENSE` file as @CCFenner described would be sufficient?

**Comment by stevesap** [comment]
@CCFenner how about a blocking Github Action which verifies that every relevant file in PR has the correct license header? If not, the PR author can then correct the issues locally either manually or by using the `license-maven-plugin` (to be documented in CONTRIBUTION.md)

As for the THIRD-PARTY-LICENSE file, pending on @tkowark 's confirmation, we could try a similar approach with respect to validating a correct THIRD-PARTY-LICENSE file as a result of relevant PR changes.

**Comment by CCFenner** [comment]
> @CCFenner how about a blocking Github Action which verifies that every relevant file in PR has the correct license header? If not, the PR author can then correct the issues locally either manually or by using the `license-maven-plugin` (to be documented in CONTRIBUTION.md)

Should be doable, I'll have a look at it tonight. Would it be sufficient to have it blocking on any missing header not only changed files? I guess this would make the job much simpler.

**Comment by stevesap** [comment]
@CCFenner thanks. Yes I think that would be sufficient if it makes it simpler.

**Comment by tkowark** [comment]
@CCFenner @stevesap Sorry for the delay in response. Please automate that process of collecting all dependencies and their licenses. For the time being, let's collect the license texts manually (they should not change that often). 

Whether you do that in the same file, a folder, or a separate file is up to you. Of course, we can support in checking the list from time to time.

**Comment by stevesap** [comment]
@CCFenner in this case, IMO, we should stick to the manually maintained single file we currently have since any addition of a license would require manual work anyways (for full license text) and also I think having everything in a single file is more readable and accessible. Thoughts?
