### ISSUE TITLE
Migrate form maven to gradle

### ISSUE THREAD

**Issue by JKL03** [corona-warn-app/cwa-server#359]
I would like to use gradle instead of maven.
XML Notation isn‘t State of the Art anymore.
Form my personal personal point of view is much more comfortable to handle. U can us .yml or other file types.

## Expected Benefits
- better overview 
- less code
- better plugin support

**Comment by johanneseschrig** [comment]
Hello Jens! Thank you for your input. Currently, we do not see any drawbacks of using maven and do not plan changing our build tool at this point.
