### ISSUE TITLE
What about GitFlow? Seem better fit.

### ISSUE THREAD

**Issue by JKL03** [corona-warn-app/cwa-server#360]
![image](https://user-images.githubusercontent.com/33860271/83200957-bf722b80-a144-11ea-90f0-8854c67f286c.png)

# Key Benefits
## Parallel Development
One of the great things about GitFlow is that it makes parallel development very easy, by isolating new development from finished work. New development (such as features and non-emergency bug fixes) is done in feature branches, and is only merged back into main body of code when the developer(s) is happy that the code is ready for release.

Although interruptions are a BadThing(tm), if you are asked to switch from one task to another, all you need to do is commit your changes and then create a new feature branch for your new task. When that task is done, just checkout your original feature branch and you can continue where you left off.

## Collaboration
Feature branches also make it easier for two or more developers to collaborate on the same feature, because each feature branch is a sandbox where the only changes are the changes necessary to get the new feature working. That makes it very easy to see and follow what each collaborator is doing.

## Release Staging Area
As new development is completed, it gets merged back into the develop branch, which is a staging area for all completed features that haven’t yet been released. So when the next release is branched off of develop, it will automatically contain all of the new stuff that has been finished.

## Support For Emergency Fixes
GitFlow supports hotfix branches - branches made from a tagged release. You can use these to make an emergency change, safe in the knowledge that the hotfix will only contain your emergency fix. There’s no risk that you’ll accidentally merge in new development at the same time.

**Comment by johanneseschrig** [comment]
Hello Jens, thank you for your input! 

Can you specify what you are missing? This is very close to what we are doing. We have feature branches, our `master` is the proposed `development` branch, our `release` branch is the proposed `master`.
