### ISSUE TITLE
Use semantic release for release management

### ISSUE THREAD

**Issue by JKL03** [corona-warn-app/cwa-server#361]
[introduction](https://semantic-release.gitbook.io/semantic-release/)

## Current Implementation
Just add plugin in maven and use it your commits
[howtouse](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716)

## Suggested Enhancement
- release management based on your commits

**Comment by johanneseschrig** [comment]
Hi Jens, thank you for your input! Currently we do use semantic versioning, as you can see here: https://github.com/corona-warn-app/cwa-server/releases.
