### ISSUE TITLE
Change cron trigger to shortly after the full hour

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#365]
## Current Implementation
Cron trigger is set to `55 * * * *`

## Suggested Enhancement
Set the cron trigger to something like `5 * * * *`

## Expected Benefits
The distribution run does not include incomplete hours. When the job runs at 55, it will not include the submissions of the past 55 minutes. When this is set to 5, only submissions from the past 5 minutes are not included. This gives clients much more recent data in a timely manner.

**Comment by christian-kirschnick** [comment]
@johanneseschrig This is already done, right?

**Comment by ole-lilienthal** [comment]
This is done
