### ISSUE TITLE
Exclude "empty" dates and hours from the index

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#366]
## Current Implementation
All completed dates and hours are in the index files, regardless of whether there have been submissions or not.

## Suggested Enhancement
Don't include dates/hours in the index for which there were no submissions as per API documentation [here](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/api_v1.json#L131) and [here](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/api_v1.json#L232) (but still generate the empty export file).

**Comment by michael-burwig** [comment]
duplicate? #140

**Comment by pithumke** [comment]
Sorry, yes. This is a duplicate.
