### ISSUE TITLE
Wrong maximum total risk score in risk score classifications

### ISSUE THREAD

**Issue by michael-burwig** [corona-warn-app/cwa-server#381]
## Describe the bug

Currently, the maximum value for a total risk score class is set to 4096.

## Expected behaviour

The [Apple documentation](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration) states:
> Level values are in the range of 0-8. Though the formula’s range can be up to 4096, the framework limits totalRiskScore to the upper limit of ENRiskScore, which has a maxium value of 255.

According to @jakobmoellersap, while Google does not seem to state this explicitly, this is reflected in their implementation.

**Comment by michael-burwig** [comment]
@christian-kirschnick do you have more context on this?

**Comment by christian-kirschnick** [comment]
Check discussion in https://github.com/corona-warn-app/cwa-server/pull/382

**Comment by christian-kirschnick** [comment]
Closing as invalid - was an issue on their end.
