### ISSUE TITLE
Project won’t build with JDK > 11

### ISSUE THREAD

**Issue by jwedel** [corona-warn-app/cwa-server#389]
# Describe the bug

When building with OpenJDK > 11 the build fails.

## Expected behaviour

The README says:
> Minimum JDK Version 11

So I would expect the project to build with any JDK > 11
## Steps to reproduce the issue

- Run `maven install` on OpenJDK 12

And you’ll get the following error when running the distribution module tests:

```
Caused by: java.lang.ClassCastException: class org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to class org.bouncycastle.openssl.PEMKeyPair (org.bouncycastle.asn1.pkcs.PrivateKeyInfo and org.bouncycastle.openssl.PEMKeyPair are in unnamed module of loader 'app')
```
## Technical details

- Host Machine OS (Windows/Linux/Mac): MacOS

## Possible Fix
- I haven’t checkt but since bouncy castle ist very common, there will certainly be a solution to it. 

## Additional context

This came up via #387.

**Comment by BjoernKW** [comment]
The build process works with OpenJDK 14. Maybe, this helps with narrowing down the issue:

openjdk version "14" 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

**Comment by jwedel** [comment]
@BjoernKW 

> The build process works with OpenJDK 14.

Did you try with 12 as well? If yes, what’s the result?

**Comment by BjoernKW** [comment]
Yes, I've just tried it with OpenJDK 12.0.2. Works as well on my machine.

**Comment by rcruzroman** [comment]
Just to let you know, I also tried with JDK 13 and it worked properly (MacOS)

**Comment by jwedel** [comment]
Ok, thx for the feedback. Then it looks as if there is an issue on my side. I will first check the exact version.

**Comment by jwedel** [comment]
Ok, the versions I've tried yet:
- OpenJDK 12.0.1 ❌
- OpenJDK 12.0.2 ✅
- OpenJDK 14.0.1 ✅

I think the first time I tried was a WIP branch of the JDK 14 for project loom...

So I'll close this!
