### ISSUE TITLE
Sonar: Make sure that using a regular expression is safe here.

### ISSUE THREAD

**Issue by johanneseschrig** [corona-warn-app/cwa-server#393]
We need to audit https://sonarcloud.io/project/issues?id=corona-warn-app_cwa-server&issues=AXJbUSaqJbMaFKmXXHJV&open=AXJbUSaqJbMaFKmXXHJV&types=SECURITY_HOTSPOT

**Comment by christian-kirschnick** [comment]
Audited - the string input here is defined by our API structure, so there is no user input involved. This is fine.
