### ISSUE TITLE
Multiple DB design and permission issues discussed on Twitter

### ISSUE THREAD

**Issue by sventuerpe** [corona-warn-app/cwa-server#412]
Alvar Freude discusses [in a Twitter thread](https://twitter.com/alvar_f/status/1267705319280586753) several possible database design issues. Their impact [remains unclear](https://twitter.com/BlackBat1987/status/1267731840665890816) to the casual reader. 

The author [promised](https://twitter.com/alvar_f/status/1267715517760131072) to create issues here on GitHub after discussing his thoughts with the Twitter crowd. Meanwhile, I leave this here as a heads-up and placeholder.

**Comment by stevesap** [comment]
Thanks for the heads-up! We encourage the community to review the thread and log further issues in our repository.
