### ISSUE TITLE
Adopt REUSE best practices

### ISSUE THREAD

**Issue by mxmehl** [corona-warn-app/cwa-server#413]
## Current Implementation

Right now, the only indication of the copyright holder and the used software license is in the README.md file at the very bottom. If people want to reuse code of this repository, it is likely they will drop this important information, or that they will have to search manually which also holds the risk of information being lost or altered.

## Suggested Enhancement

Follow the [REUSE](https://reuse.software) best practices for declaring copyright and licensing information. In practice for this repo, this means:

- [ ] Add the copyright holder (SAP) and the license (Apache-2.0) in a standardised form to each file of the repo. Check with the [REUSE helper tool](https://github.com/fsfe/reuse-tool) whether all information is available and correct.
- [ ] Add the REUSE lint to the CI. For CircleCI, there is no guide on how to do that at the moment (but for [many other CIs](https://reuse.software/dev/#ci)), but it won't be hard probably.

I would be happy to contribute a Pull Request on this if wanted.

## Expected Benefits

The code of this repo would be much easier and safer to reuse by others – individuals and other countries. Having the information available makes license compliance smooth and the original copyright holders with their licensing choice persistent. It's a low-hanging-fruit best practice with some big impact.

**Comment by johanneseschrig** [comment]
Hello Max, thank you for your proposal! 

Currently, we decorate all [files with a copyright header](https://github.com/corona-warn-app/cwa-server/blob/master/services/submission/src/main/java/app/coronawarn/server/services/submission/ServerApplication.java#L2) and use the [maven license plugin](https://github.com/corona-warn-app/cwa-server/blob/master/pom.xml#L47). Can you specify what functionality you are missing?

**Comment by mxmehl** [comment]
Thanks for the swift reply!

First of all, REUSE asks to label *all* files with licensing and copyright information, this makes reusing the whole project easy.

Then, the best practices involve using standardised tags to serve various tooling. The Copyright line is fine (although we recommend using something like `SPDX-FileCopyrightText: 2020 SAP SE`. Regarding the license, the text blob at the header would be replaced by `SPDX-License-Identifier: Apache-2.0`.

The SPDX tags are widely understood in industry and community, and various tools like FOSSology, SW360, or Scancode depend on it. They greatly avoid ambiguity.

So, in summary, the file you linked to could look like the following (I omitted the `---license-start` because I'm not sure how it's being used exactly:

```java
/*-
 * Corona-Warn-App
 * ---
 * SPDX-FileCopyrightText: 2020 SAP SE and all other contributors
 * SPDX-License-Identifier: Apache-2.0
 * ---
 */

package app.coronawarn.server.services.submission;
[...]
```

The whole Apache license text, as well as potential additionally used licenses, would then be collected in a `LICENSES/` directory. If you want to see a simple example repo which is REUSE compliant, see [here](https://github.com/fsfe/reuse-example/). It sounds more complicated than it actually is, so I'm happy to start this process with a Pull Request.

Additionally, it could make sense to add additional copyright holders directly in the file. So if Jane Doe contributed to `ServerApplication.java` in a degree that justifies naming her as Copyright holder, you can just duplicate the `SPDX-FileCopyrightText` line, including her name. A reference to a Authors file could also work, REUSE does not mandate anything specific here.

**Comment by stevesap** [comment]
Thanks for the suggestion. We have reviewed it and found our current license headers sufficient for our purposes.
