### ISSUE TITLE
Distribution: Add Safeguard to not generate any exposure key file > 16MB

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#444]
In order to prevent issues on the mobile device & potential abuse, add a safeguard, so that we do not publish any files, which are bigger than 16MB. In case this threshold is reached for any file, an error message must be logged.

Make sure to keep consistency with the index files. In order to align with the current concept of always generating a file, we should generate an empty file in this case as well.

@pithumke

**Comment by michael-burwig** [comment]
> In order to align with the current concept of always generating a file, we should generate an empty file in this case as well.
Will skip generating files larger than 16 MB in order to stay constistent with the current implementation.
