### ISSUE TITLE
API documentation out of sync with implementation

### ISSUE THREAD

**Issue by michael-burwig** [corona-warn-app/cwa-server#456]
``services/distribution/api_v1.json`` is currently out of sync with the implementation for the app configuration parameter distribution.

E.g., the endpoint described in the image below does not exist any more.
![image](https://user-images.githubusercontent.com/64439292/83869433-dd372600-a72c-11ea-8772-54458bb84a8a.png)

**Comment by christian-kirschnick** [comment]
https://github.com/corona-warn-app/cwa-server/issues/372
