### ISSUE TITLE
Generate JavaDoc

### ISSUE THREAD

**Issue by stevesap** [corona-warn-app/cwa-server#496]
# Suggested Enhancement

As we have already authored extensive JavaDoc within code, it would be beneficial to generate JavaDoc documentation in order to:
- Provide easy to navigate class structure/documentation for newcomers and existing contributors alike.
- Easily refer/link to classes from the [external cwa-server documentation](https://github.com/corona-warn-app/cwa-server/tree/master/docs) 

TBD: where to host?

**Comment by robertoduessmann** [comment]
Hey @stevesap , a good alternative to host the javadocs is https://www.javadoc.io/. It's free for open source projects.

I think all we have to do is make sure cwa-server is published to Central Maven or Bintray (JCenter).

If it sounds ok, I can help trying to setup the project with Central Maven.
Later on, javadoc.io is able to fetch the artefacts from there and make available the javadocs.

**Comment by stevesap** [comment]
Hi @robertoduessmann thanks for your suggestion. We considered it but decided to settle on hosting the JavaDoc on our [gh-pages](https://github.com/corona-warn-app/cwa-server/tree/gh-pages) branch.

JavaDoc available at https://corona-warn-app.github.io/cwa-server/index.html
