### ISSUE TITLE
Optimize distribution process for memory usage

### ISSUE THREAD

**Issue by stevesap** [corona-warn-app/cwa-server#538]
## Current Implementation

The Distribution module currently builds and holds a complete file directory tree in memory before writing to disk. And while each file ultimately written to disk cannot exceed 16 MB, they could (theoretically) also go above 16 MB in memory, as the files that go above that limit are only filtered out during the "write" step (when they are written to disk), but not during the "prepare" step (where their content is being assembled).

Therefore, total memory usage during a distribution could in theory grow quite large and may result in an OutOfMemory error.

## Suggested Enhancement

Make the following suggested optimizations:

- Merge "prepare" and "write" into a single step
- Paginate diagnosis key DB requests (don't query everything at once, but only when required/writing)
- Use streams instead of allocations where ever possible

## Expected Benefits

More efficient memory usage and avoid any potential OutOfMemory errors.

Note: This ticket was the result of question #517

**Comment by jsievers** [comment]
did you fix the issue? wondering why it's closed now
