### ISSUE TITLE
Missing a call to shutdown() on newSingleThreadScheduledExecutor

### ISSUE THREAD

**Issue by thebpc** [corona-warn-app/cwa-server#542]
## Describe the bug

Missing a call to shutdown() on java.util.concurrent.Executors.newSingleThreadScheduledExecutor [:63] - the executor is not shut down, which may lead to a resource leak or to a hanging application.
Line 63
file: services/submission/src/main/java/app/coronawarn/server/services/submission/controller/ SubmissionController.java

## Expected behaviour

setting down the  executor 

## Steps to reproduce the issue

This was detected by www.deepcode.ai through source-code analysis and not dynamic execution

## Technical details

N/A

## Additional context

The exact explanation can be seen here after a GitHub log-in, there is no need to add any of your reports for live monitoring and GitHub will give you that option during LogIn.

 https://www.deepcode.ai/app/gh/corona-warn-app/cwa-server/46fa39c095bc428620abd9e658353677ded64b04/_/%2Fservices%2Fsubmission%2Fsrc%2Fmain%2Fjava%2Fapp%2Fcoronawarn%2Fserver%2Fservices%2Fsubmission%2Fcontroller%2FSubmissionController.java/java%2Fdc%2Fmissing~shutdown~java.util.concurrent.Executors.newSingleThreadScheduledExecutor/63/code#

There are a number of others missing closes to BufferedReader, FileOutputStream, leaking resource and one performance optimization.

Feel free to enable the DeepCode bot it is free for Open Source and securely monitors all your new PRs as well as your existing code for new issues learned by AI models from the global development community.

**Comment by stevesap** [comment]
Dup of #433
