### ISSUE TITLE
Add JPA range validator for submissionTimestamp of DiagnosisKey

### ISSUE THREAD

**Issue by jsievers** [corona-warn-app/cwa-server#557]
DiagnosisKey uses a submissionTimestamp field of type long

https://github.com/corona-warn-app/cwa-server/blob/7059232b48d2507d142fe683fbebdda371a98652/common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java#L73 

the value is actually the *hours* since epoch but there are no sanity checks on the value.

Just from reading the code you could e.g. easily think it's seconds since epoch and use it the wrong way without noticing at runtime.

Proposal:

* Add a JPA ConstraintValidator similar to ValidRollingStartIntervalNumberValidator which checks the value range to be greater or equal zero and not in the future (current hour since epoch rounded up)
* Add field javadoc to submissionTimestamp: "hours since epoch"

Expected Benefits:

* discard invalid data
* less potential for programming errors

**Comment by jsievers** [comment]
I could open a PR wit the proposal if you think it makes sense

**Comment by jsievers** [comment]
the getter and Builder already  do have javadoc "hours since epoch" 

https://github.com/corona-warn-app/cwa-server/blob/master/common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyBuilders.java#L80

so it's actually documented. Would still be nice to validate it though.

**Comment by stevesap** [comment]
@jsievers makes sense. Please go ahead with a proposal PR.
