### ISSUE TITLE
S3ClientWrapper getObjects: Not all objects could be received

### ISSUE THREAD

**Issue by thwefl** [corona-warn-app/cwa-server#562]
## Describe the bug

https://github.com/corona-warn-app/cwa-server/blob/a953c054f8b4dc97d6a40525c5c3d5aa4d867394/services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/client/S3ClientWrapper.java#L83

It is possible that not all objects are received, because the **listObjectsV2(ListObjectsV2Request listObjectsV2Request)** method  limits them up to 1000.

Javadoc [listObjectsV2](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#listObjectsV2-software.amazon.awssdk.services.s3.model.ListObjectsV2Request-)
> Returns some or all (up to 1,000) of the objects in a bucket.

## Possible Fix

1. Checking the response for more data with the **isTruncated** method.
JavaDoc [isTruncated](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/ListObjectsV2Response.html#isTruncated--)
> Set to false if all of the results were returned. Set to true if more keys are available to return. If the number of results exceeds that specified by MaxKeys, all of the results might not be returned.
2. When the response is truncated, calling the **nextContinuationToken** method for the next token.
JavaDoc [nextContinuationToken](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/ListObjectsV2Response.html#nextContinuationToken--)

> NextContinuationToken is sent when isTruncated is true, which means there are more keys in the bucket that can be listed. The next list requests to Amazon S3 can be continued with this NextContinuationToken.

3. Build a new ListObjectsV2Request with the **continuationToken** and call **listObjectsV2** again
JavaDoc [continuationToken](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/ListObjectsV2Request.Builder.html#continuationToken-java.lang.String-)

> ContinuationToken indicates Amazon S3 that the list is being continued on this bucket with a token. ContinuationToken is obfuscated and is not a real key.

4. Repeat everything until isTruncate is false.

Here is a pretty good example from AWS. They use a different S3Client, but it is very similar to the one you use. ([source](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingObjectKeysUsingJava.html))

```java
import com.amazonaws.AmazonServiceException;
import com.amazonaws.SdkClientException;
import com.amazonaws.auth.profile.ProfileCredentialsProvider;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.ListObjectsV2Request;
import com.amazonaws.services.s3.model.ListObjectsV2Result;
import com.amazonaws.services.s3.model.S3ObjectSummary;

import java.io.IOException;

public class ListKeys {

    public static void main(String[] args) throws IOException {
        Regions clientRegion = Regions.DEFAULT_REGION;
        String bucketName = "*** Bucket name ***";

        try {
            AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                    .withCredentials(new ProfileCredentialsProvider())
                    .withRegion(clientRegion)
                    .build();

            System.out.println("Listing objects");

            // maxKeys is set to 2 to demonstrate the use of
            // ListObjectsV2Result.getNextContinuationToken()
            ListObjectsV2Request req = new ListObjectsV2Request().withBucketName(bucketName).withMaxKeys(2);
            ListObjectsV2Result result;

            do {
                result = s3Client.listObjectsV2(req);

                for (S3ObjectSummary objectSummary : result.getObjectSummaries()) {
                    System.out.printf(" - %s (size: %d)\n", objectSummary.getKey(), objectSummary.getSize());
                }
                // If there are more than maxKeys keys in the bucket, get a continuation token
                // and list the next objects.
                String token = result.getNextContinuationToken();
                System.out.println("Next Continuation Token: " + token);
                req.setContinuationToken(token);
            } while (result.isTruncated());
        } catch (AmazonServiceException e) {
            // The call was transmitted successfully, but Amazon S3 couldn't process 
            // it, so it returned an error response.
            e.printStackTrace();
        } catch (SdkClientException e) {
            // Amazon S3 couldn't be contacted for a response, or the client
            // couldn't parse the response from Amazon S3.
            e.printStackTrace();
        }
    }
}
``

**Comment by michael-burwig** [comment]
Thanks for the good find @thwefl.
The good news is that considering the current design, we can confidently expect the number of returned elements to be way below 500.
But nontheless, you are right in that it would not hurt to make this a little more robust.
I suggest to use supply ``S3Request.Builder.maxKeys`` with a satisfyingly large value such as ``5000`` and log a warning/error if ``ListObjectsV2Response.isTruncated`` returns ``true``.

Best,
Michael

**Comment by thwefl** [comment]
Hej Michael,
thanks for the quick response. Your proposed changes sounds good.
I know it's  small issue, but when it occurs, it is hard to find.

Best,
thwefl
