### ISSUE TITLE
Reliability improvement: Avoid doing database migration on application startup

### ISSUE THREAD

**Issue by shyamz-22** [corona-warn-app/cwa-server#565]
## Current Implementation
In the current setup we see that the flyway migrations are done in the application startup

## Suggested Enhancement
To extract this step out of the application startup, use the flyway-cli as task to run the migration commands

## Expected Benefits
On cloud infrastructures like Kubernetes the liveness/readiness  determines if the application came up healthy. These are typically associated with short timeouts.

When there is a migration script that needs more than the application liveness/readiness probe  timeouts (Ex: When deleting a column that was previously indexed), then the underlying infrastructure marks them as un healthy and tries to restart them over and over again.

When the migration step is extracted as a separate task then this behaviour can be avoided

You can find detailed information here: https://pythonspeed.com/articles/schema-migrations-server-startup/#:~:text=Migrations%20on%20application%20startup%20are,schema%20and%20code%20in%20sync.

**Comment by stevesap** [comment]
Thanks for the suggested enhancement. We have looked into possible solutions but as our schema is fairly simple, we do not believe the additional complexity of extracting the migration step is necessary at this point.
