### ISSUE TITLE
Avoid flyway migrations for the same database in both services

### ISSUE THREAD

**Issue by shyamz-22** [corona-warn-app/cwa-server#568]
## Describe the bug

Flyway migration is done from both [Submission Service](https://github.com/corona-warn-app/cwa-server/blob/fac7b887681497d1a320f943d272568b314c6c22/services/submission/src/main/resources/application.yaml#L29) and [Distribution Service](https://github.com/corona-warn-app/cwa-server/blob/fac7b887681497d1a320f943d272568b314c6c22/services/distribution/src/main/resources/application.yaml#L64)

## Expected behaviour

- There will be single responsibility on which service does migration to **avoid race conditions that both services attempt to do migration at the same time**.

- If a migration fails it will be **easy to check one responsible service rather than both**. 

## Steps to reproduce the issue

N/A

## Technical details

N/A

## Possible Fix

Disable flyway migration from submission service, As this is a server used by Corona Warn App, and as mentioned in the issue #565 **migration on application startup should be avoided**

## Additional context

N/A

**Comment by johanneseschrig** [comment]
Hi Syamala! 
Thanks for your input! We had similar concerns before we introduced this, however, the [Flyway documentation](https://flywaydb.org/documentation/faq.html#parallel) states that parallel migrations should not be an issue.

**Comment by christian-kirschnick** [comment]
Closing this issue as Flyway handles concurrency accordingly.
