### ISSUE TITLE
Enable IPv6 for submission and verification server

### ISSUE THREAD

**Issue by Bombenleger** [corona-warn-app/cwa-server#577]
## Current Implementation
In production, only the distribution CDN is reachable via IPv6.
Both, submission and verification server do not have AAAA records announced in DNS and are therefor IPv4 only.

## Suggested Enhancement
Make all endpoints reachable via IPv6 and add corresponding DNS records.

## Expected Benefits
This change avoids NAT and makes the services reachable from IPv6-only networks too, in order to reach as many people as possible,

**Comment by stevesap** [comment]
Thanks for the suggestion. It has been transferred to our Infrastructure team.
