### ISSUE TITLE
Docker containers should not be run as root inside the container

### ISSUE THREAD

**Issue by ko1N** [corona-warn-app/cwa-server#593]
It is advisable to not run the server processes inside the docker container with root privileges as this might give a potential attacker additional freedom (e.g. abusing syscalls).

Both Dockerfiles provided should run the server process as a user other than root:

https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/Dockerfile
https://github.com/corona-warn-app/cwa-server/blob/master/services/submission/Dockerfile

Kind regards

**Comment by stevesap** [comment]
See https://github.com/corona-warn-app/cwa-server/issues/451#issuecomment-640053082

**Comment by ko1N** [comment]
> See [#451 (comment)](https://github.com/corona-warn-app/cwa-server/issues/451#issuecomment-640053082)

I am not referring to the SQL user (which should easily be configurable in your deployment setup) but about actually running the processes as root user inside the Docker container.

If you don't use the Dockerfiles in your production env this should be fine however.

**Comment by stevesap** [comment]
Thanks @ko1N I confirmed now this is an issue. PR #597 opened.
