### ISSUE TITLE
Move SubmissionController logic into extra service

### ISSUE THREAD

**Issue by cyber655** [corona-warn-app/cwa-server#595]
## Current Implementation
Currently there is much business logic in the **/services/submission/src/main/java/app/coronawarn/server/services/submission/controller/SubmissionController.java.**

## Suggested Enhancement
This should be moved into an extra service layer.

## Expected Benefits
Better architecture and readability.

**Comment by stevesap** [comment]
See PR:  https://github.com/corona-warn-app/cwa-server/pull/554
