### ISSUE TITLE
In Exposure Config master file: Value for Duration Risk 10< D <= 15 minutes is not set correctly (1 instead of 0)

### ISSUE THREAD

**Issue by twenta** [corona-warn-app/cwa-server#601]
## Describe the bug

Currently, exposure is also assumed for contact with duration more than 10 minutes to 15 minutes in the exposure config file https://github.com/corona-warn-app/cwa-server/blob/eb8be6c3e9c723c62c619784e41889d10054cc93/services/distribution/src/main/resources/master-config/exposure-config.yaml#L34

## Expected behaviour

Exposure should only be considered when duration of contact was more than 15 minutes and risk level value for 10< D <= 15 should be set to 0:
`gt_10_le_15_min: 0`

## Possible Fix
Change line 34:
`duration:
  eq_0_min: 0
  gt_0_le_5_min: 0
  gt_5_le_10_min: 0
  **gt_10_le_15_min: 0**
  gt_15_le_20_min: 1
  gt_20_le_25_min: 1
  gt_25_le_30_min: 1
  gt_30_min: 1`

## Additional context

It is widely communicated that the minimum duration of a contact to be considered for contact tracing is **more than 15 minutes** (see e.g. by WHO https://www.who.int/publications/i/item/contact-tracing-in-the-context-of-covid-19). This was also repeatedly mentioned in the press conference today by Lothar Wieler (https://www.youtube.com/watch?v=GDnaNMGbXnw e.g. minute 48:30).

**Comment by corneliusroemer** [comment]
@stevesap  I'm not sure the reasoning is correct.

Shouldn't exposure be a continuous thing? If you interact with 3 infected people for 5min each, that's equivalent to 1 person for 15min. So the risk level should increase until a threshold is reached.

Thanks @twenta for finding out where the exposure config is. I had no idea but was looking for it!

This is a big change, is there a reference somewhere in the documentation that explains how the settings should be? @twenta uses WHO documents, but this is quite app centric, so it should be in the scoping docs.

@tkowark @SebastianWolf-SAP @jakobmoellersap Do you have any ideas about this? Just quoting WHO shouldn't be enough. Where is the spec located for what config values should be? Or is there no spec?

**Comment by BenzlerJ** [comment]
For further information please also refer to https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md and https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf.

**Comment by corneliusroemer** [comment]
@BenzlerJ thanks for linking to the documents, but both of them are too general, they don't explain what particular values were chosen and why, for the risk calculation parameters given to the exposure api.

Do you know where these very important concrete choices are documented?

**Comment by twenta** [comment]
From reading the documentation (sorry couldn't find it before), it becomes clear that exposures between 10-15 min are further evaluated and taken into account in case the attenuation suggest a very close contact during this time. So this very likely not a bug.

> the time remains unchanged if this risk is estimated as average (for risk exposures), it is extended to one and a half times if the risk is above average, and it is reduced significantly (to around one-sixth) if the risk is below average. As a result, a**n exposure time of 10 minutes can be extended to more than 15 minutes** and an exposure time of 45 minutes can be reduced to less than 10 minutes.
https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md

**Comment by corneliusroemer** [comment]
@twenta While you may be right that it's not a clear bug as such, the reasons for choosing the particular values that are set does not appear clear to me - it doesn't seem properly documented. https://github.com/corona-warn-app/cwa-documentation/issues/257

A binary choice seems to be made for risk based on whether contact is for more or less than 10min with an exposed person per day. That doesn't seem good to me - at least it needs to be properly argued for why risk should not increase continuously with increased exposure time.

I would like to invite you to try to work this out with me. @BenzlerJ is helping me there, he seem to know about this, maybe was even the person who set the values. But I'd appreciate your input on this important and not sufficiently documented issue.

Security got a lot of attention, now the apps are getting attention. But these risk parameters are not - even though they are extremely important.

**Comment by pdehaye** [comment]
@corneliusroemer I do agree the setting of those parameters is extremely important. For this reason I have consolidated all the outstanding questions, to the best of my ability, in #336.
