### ISSUE TITLE
CWA Hash should also incorporate the signing information

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#606]
We are currently using the `export.bin` payload in order to compute the checksum. This approach does not reflect the signing information, which is part of the `export.sig`. Therefore, if the key would be rolled at some point in time, the cwa hash will not change, and hence the system will not re-distribute the files with the new signature information.

Therefore, the key cwa hash should also reflect the key, which was used for signing they `export.bin` payload.

Current is:
https://github.com/corona-warn-app/cwa-server/blob/cd4eb1af6f8f60ae2b97759cbdeaaead84a20f13/services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/file/FileOnDiskWithChecksum.java#L75-L80

**Comment by mibrasap** [comment]
The checksum already incorporates the signature info, see test in PR #621
