### ISSUE TITLE
iOS 14 COVID-19-Contactprotokoll not active

### ISSUE THREAD

**Issue by RalphRichter** [corona-warn-app/cwa-server#616]
In iOS 14.0 Developer Beta contact Protokoll not active in privacy settings.

Corona-Warn-App latest App Store Release not shown as active

![image](https://user-images.githubusercontent.com/67153468/85341353-36060d00-b4e8-11ea-90c8-f8dd326c4b57.png)

![image](https://user-images.githubusercontent.com/67153468/85341361-3b635780-b4e8-11ea-9ac8-fc9752fe0570.png)

**Comment by christian-kirschnick** [comment]
He @RalphRichter,

iOS 14 does not yet support the Exposure Notification Framework - also see https://github.com/corona-warn-app/cwa-app-ios/issues/749.

Please use the cwa-app-ios repository if you need any additional support on the mobile app side.

cheers
Christian
