### ISSUE TITLE
Overlapping risk classes where overlapping is forbidden in risk-score-classification.yaml

### ISSUE THREAD

**Issue by dideldei** [corona-warn-app/cwa-server#630]
In risk-score-classification.yaml,
a low risk class is defines from 0-15 and a high risk class from 15-72. So 15 is "owned" by both classes which is described as a "must not" in the files documentation.

**Comment by mh-** [comment]
For reference: The Android app currently uses (only) the values from the "HIGH" class: https://github.com/corona-warn-app/cwa-app-android/blob/da694a5838ee10362d4a370af43a8a0064e7da74/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt#L384

**Comment by christian-kirschnick** [comment]
This is an issue in the documentation which should be fixed.

The risk score used by this configuration value is actually a decimal value - which was an integer before. Guess the documentation was not adjusted accordingly when the change was made.

**Comment by christian-kirschnick** [comment]
@michael-burwig Can we close this?
