### ISSUE TITLE
Wrong risk values for old android users.

### ISSUE THREAD

**Issue by Tho-Mat** [corona-warn-app/cwa-server#640]
## Describe the bug
some time ago "Diagnosis Keys Upload: Transmission Risk Levels are applied in reverse order"
has been fixed. (https://github.com/corona-warn-app/cwa-app-android/issues/678)
So infected users with a newer Android version send the risk values in the right order.
I assumed, with the the fix on the client side, the problem goes away. 
But when you lock on, for example 
https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date/2020-06-28
, you will see there are still users that submit the risk in the wrong order. 
21-06-20 10 key with risk 6
22-06-20 10 key with risk 8
23-06-20 10 key with risk 8
24-06-20 10 key with risk 8
25-06-20 10 key with risk 5
26-06-20 10 key with risk 3
27-06-20 10 key with risk 1
https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date/2020-06-27
17-06-20 10 key with risk 6
18-06-20 10 key with risk 7
19-06-20 10 key with risk 8
20-06-20 10 key with risk 7
21-06-20 10 key with risk 5
22-06-20 10 key with risk 3
23-06-20 10 key with risk 2
24-06-20 10 key with risk 1
25-06-20 10 key with risk 1
26-06-20 10 key with risk 1

With this wrong submission  a user with contact to the key "26-06-20 10 key with risk 1" will get a low risk info. But with the right risk value of 6 it would be much higher. On the other hand a user with contact to 
"17-06-20 10 key with risk 6" gets high risk info, but it should be low.

## Expected behaviour

To fix the client side bug, also a server side fix is needed. 

for 2020-06-28 in the above example it should be:
21-06-20 10 key with risk 1
22-06-20 10 key with risk 3
23-06-20 10 key with risk 5
24-06-20 10 key with risk 8
25-06-20 10 key with risk 8
26-06-20 10 key with risk 8
27-06-20 10 key with risk 6
for 2020-06-27 in the above example it should be:
17-06-20 10 key with risk 1
18-06-20 10 key with risk 1
19-06-20 10 key with risk 1
20-06-20 10 key with risk 1
21-06-20 10 key with risk 3
22-06-20 10 key with risk 5
23-06-20 10 key with risk 8
24-06-20 10 key with risk 8
25-06-20 10 key with risk 8
26-06-20 10 key with risk 6

So to fix the client side change in the profile (5,6,7,8,7,5,3,2,1) to (5,6,8,8,8,5,3,1,1) 
and the "Diagnosis Keys Upload: Transmission Risk Levels are applied in reverse order"  bug
a server side fix is also needed. 

## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by christian-kirschnick** [comment]
Most Android clients have already 1.0.4 running - unfortunately, roughly 10% are still running the older 1.0.2 version which is affected. We will push out release [1.0.9](https://github.com/corona-warn-app/cwa-server/releases/tag/v1.0.9) hopefully today, which will enforce an update on older Android clients. This will solve the problem.

**Comment by Tho-Mat** [comment]
A fix on the client side will not fix it for users that are running and old version? 
But, if it is possible to "force" an update on client side, even the user is running an old version,
than that would fix the problem. 
I do not know if that is possible. 
Does that mean an old version (1.0.2) can not transmit values after 1.0.9 is published?

On the other hand it would be very easy to change the risk values immediately after a user has send them to the server and before they are published.

**Comment by christian-kirschnick** [comment]
When the 1.0.9 server patch is delivered, all Android CWA apps which are not 1.0.4, will be forced to update to 1.0.4. If they are not updating, they will not be able to use the app.

**Comment by Tho-Mat** [comment]
Sound good. 
That will fix it.
Thanks.

**Comment by Tho-Mat** [comment]
@christian-kirschnick 

https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date/2020-06-30 and
https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date/2020-06-30/hour/17 

still contain 5,6,7,8,7,5,3,2,1,1,1,1,1,1 in wrong order.

So how can I check:
1. that server version 1.0.9 is online now?
2. and, if 1.0.9 is online, the time it gets online? 

If it was online before 17:00 UTC, the server fix does not work.

Since "release" shows version: 1.0.9 and 3 days ago.
Or is "release" the next release, that will be pushed.

**Comment by christian-kirschnick** [comment]
I will close this ticket when 1.0.9 is online. At the moment 1.0.8 is still deployed.

**Comment by christian-kirschnick** [comment]
1.0.9 is now live - therefore all Android clients below 1.0.4 are now deprecated and will be forced to update to 1.0.4.
