### ISSUE TITLE
Plausible Deniability: Add "Padding" property to submission payload

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#658]
Currently, mobile apps are collecting keys based on their install date. When a user uploads his keys (after being tested positive), the payload will contain 1-13 keys. Although the traffic between mobile & server is secured, an attacker may still sniff the packages in the network and predict, based on the request size, how many keys are probably part of the submission request. This may then lead to additional information for the attacker in an attempt to deanonymize a user.

In order to mitigate this attack, add a new field to the submission payload, called `padding` of type string. The field shall be optional and must not break compatibility to the current/older mobile implementations (which should be given due to the use of protobuf). The server shall not process this field.

**Comment by mussaizadini** [comment]
is amaizing one

**Comment by GPclips** [comment]
@KevponSAP do we have any update on https://github.com/corona-warn-app/cwa-backlog/issues/22 this has been referred by @tkowark

**Comment by KevponSAP** [comment]
@GPclips the padding feature was merged on July 20
