### ISSUE TITLE
Only 7 days of keys checked on 2020-07-11

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-server#663]
## Describe the bug

Today I only see 7 checks in my app on iPhone. It should be 14. I suspect the backend failed to send all keys in a way that iOS devices pick them up. 

## Expected behaviour

It should be 14 days worth of keys. 

## Steps to reproduce the issue

Simple. Let app perform check. 

## Technical details

- Host Machine OS (Windows/Linux/Mac):

## Additional context

Screenshot from iOS app showing only 7 checks. 

![image](https://user-images.githubusercontent.com/873028/87219360-9e634400-c35a-11ea-9358-a12ec3925e11.png)

**Comment by christian-kirschnick** [comment]
Was fixed with https://github.com/corona-warn-app/cwa-app-ios/pull/893
