### ISSUE TITLE
Provide statistics of key downloads from server

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-server#683]
Can you provide some anonymized statistics of the number of exposure key downloads from the server? This could help in estimating the number of **active** and **working** installations of the app. As we all know, this is a critical information and the whole purpose of the project to get a high coverage in the population.

The needed information is I think very minimal. Just the number of API calls for key downloads to the server per day would be enough I think.

**Comment by christian-kirschnick** [comment]
@SebastianWolf-SAP

**Comment by SebastianWolf-SAP** [comment]
The Robert Koch Institute as publisher reserves the exclusive right to publish statistics concerning the Corona-Warn-App. Up-to-date numbers are available on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html. The data that you have requested is currently not available there, but we will address this request to RKI. You can also reach out to them directly if you want.

As your request is already mentioned in an existing wishlist item, https://github.com/corona-warn-app/cwa-wishlist/issues/125, we will close this issue as duplicate. Thank you for your understanding.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by mss1010** [comment]
Ok, thats unfortunate, that the RKI has the exclusive rights on this. Before I ask them, I will consider talking to a wall, which is probably more enlightening.

**Comment by micb25** [comment]
> The Robert Koch Institute as publisher reserves the exclusive right to publish statistics concerning the Corona-Warn-App. Up-to-date numbers are available on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html. The data that you have requested is currently not available there, but we will address this request to RKI. You can also reach out to them directly if you want.
> 
> As your request is already mentioned in an existing wishlist item, [corona-warn-app/cwa-wishlist#125](https://github.com/corona-warn-app/cwa-wishlist/issues/125), we will close this issue as duplicate. Thank you for your understanding.
> 
> Mit freundlichen Grüßen/Best regards,
> SW
> Corona Warn-App Open Source Team

Unfortunately, this exclusive right led to the current situation in which we didn't have get any new statistics for the last two weeks.
