### ISSUE TITLE
unexpected number of keys for 2020-08-04 hour 09

### ISSUE THREAD

**Issue by Tho-Mat** [corona-warn-app/cwa-server#693]
## Your Question
* Question: did you change the key multiplier twice for this hour file? 
or is there something wrong?

**Comment by hilmarf** [comment]
Hi @Tho-Mat,

why? What's wrong with that hour file? What are you expecting?
I'm not aware of any changes.

Regards,
Hilmar

**Comment by Tho-Mat** [comment]
Risk; Date; num of keys
1	28.07.2020	   9
1	27.07.2020	  14
1	26.07.2020	  10
1	25.07.2020	   5
1	24.07.2020	  10
1	23.07.2020	  10
1	22.07.2020	   5

3	29.07.2020	  14

5	30.07.2020	  14

6	03.08.2020	  15

8	02.08.2020	  14
8	01.08.2020	  14
8	31.07.2020	  14


Normally the number of keys is a power of 5.  But this hour file is different. Either the fake factor has changed from 5 to 1 and then back to 5 or something is wrong with the file

**Comment by Tho-Mat** [comment]
I have checked all hour files since the beginning. 
And starting from 23.06 this is the only hour file that does not match.

**Comment by EvgeniiSkrebtcov** [comment]
Hello @Tho-Mat,
Thank you for the analysis. We are reviewing this topic with the team and will get back to you with a detailed answer.

Initial suspicion: 
- multiplication factor change
- possible edge case due to a sequential generation of the submission timestamps
- retention / shifting policies

Regards,
Evgenii

**Comment by EvgeniiSkrebtcov** [comment]
Hello @Tho-Mat, 

First of all, we can confirm that the multiplier was not changed. 

After reviewing the issue, we concluded that somebody uploaded their keys twice for the time frame 27.07 through 02.08. It explains why the number of keys is not a multiple of 5 and a specific pattern in that hour file:
- from 22.07 to 26.07  the number of keys is OK (multiple of 5)
- 27.07 through 02.08 are always off by one (9 or 14)
- and 03.08 is fine again

For each day, this would cause:
- 4 fake keys will be persisted in the database;
- 1 real key will be thrown away as duplicate (key_data column is the primary key, so there's a UNIQUE constraint on that column). This situation does not result in exception as the INSERT is performed with the ON CONFLICT DO NOTHING clause;

Regards,
Evgenii

**Comment by Tho-Mat** [comment]
@EvgeniiSkrebtcov 
So if I understand you right for the dates 02.08 to 27.07 
8 Fake keys have be created for 1 normal key.
1+4  and 0+4

~~But I do not understand why the user~~
~~1. could upload his keys twice.~~
~~2. the key for 03.08 (risk 6) and the keys 26.06-23.07(risk 1) where not uploaded twice.~~

The only possibilities I see is:
user upload his 1. test result on 3.8 at hour file 08 with dates 02.08 to 27.07
then upload his 2. test result on 4.8 at hour file 09 with dates 03.08 to 27.07(keys 02.08-27.07 are the same)

for the 2. upload 1+4 keys where  added to the database for 03.08. (risk 6)
and 0+4 keys where added to the database for 02.08-27.07 (risk 8,8,8,5,3,1,1)

So, to avoid this, no fake keys should be created for keys already in the database. 
But that may not be easy to do, if fake keys are added to the upload before the upload is added to the database.

**Comment by mh-** [comment]
I don't feel that any change is required at cwa-server, now that we know that nothing went wrong.
While I would like my [tools](https://github.com/mh-/diagnosis-keys) to always calculate correct numbers, I think this has no priority compared to the original use case of cwa-server.

**Comment by fredrb** [comment]
Thanks everyone for the inputs, we are closing this issue. If there is any suggestion please file a new issue with the `enhancement` tag.
