### ISSUE TITLE
Reduce the minimum number of key to 130

### ISSUE THREAD

**Issue by Tho-Mat** [corona-warn-app/cwa-server#701]
The minimum number of diagnosis keys per bundle.
    shifting-policy-threshold: 140

I think this value was initial selected since 140 = 14*10 (14 days 10 users).

Unfortunately each user uploads a maximum of 13 keys.

What is the side effect of  this selection?
Let's have a look on the keys uploaded on 02.08.2020 (just an example).
After the 2020-08-02-hour-16 file was published 2 users uploaded their keys.
Both of them uploaded 13 keys. So with the fake keys the number of keys was only 130.
As a result the keys were not included and published with the day file 2020-08-02.
They were published at 04.08.2020 2:05 (German time) with the 2020-08-03 day file. 

So at the moment a minimum of 3 users is needed to publish their key.

## Current Implementation

    shifting-policy-threshold: 140

needs at least **3** users before keys can be published

## Suggested Enhancement

    shifting-policy-threshold: 130

needs at least **2** users before keys can be published

## Expected Benefits

As long as it is not possible to check the uploaded keys hourly, with this small adjustment the example above would be published at least 24h quicker.  This also effects the hour files.

**Comment by EvgeniiSkrebtcov** [comment]
Hello @Tho-Mat,

Thank you for the suggested enhancement. Based on the analysis of the current data, it looks like a reasonable proposal.
Unfortunately, we can't adjust it immediately as 140 as a value defined by RKI, but we will address this request to RKI.

Further more, we are preparing for the upcoming [Exposure Notification API change](https://developers.google.com/android/exposure-notifications/exposure-notifications-api) (see description for getTemporaryExposureKeyHistory() method):

> Planned for a future release but not currently activated in v1.5: The keys returned include the current day’s key, which is tagged
> with an expiration date (rollingPeriod). When the current key is released, the device stops using it to generate BLE beacons, and
> replaces it with a new key. Calling this causes a new key to be selected for the remainder of the current day. As a result, if this
> method is called multiple times, several keys with different rollingPeriod and identical rollingStartNumber can be released for
> those days it was called on.

As a result, more than 14 TEKs will be submitted to the backed.

**Comment by EvgeniiSkrebtcov** [comment]
Hello @Tho-Mat ,
as planned, we raised the topic to RKI. They will analyze it and, if required, we will include the change into one of our upcoming releases.

**Comment by Tho-Mat** [comment]
@EvgeniiSkrebtcov 
Any news from RKI?

**Comment by Tho-Mat** [comment]
@EvgeniiSkrebtcov @fredrb 
sorry for asking again: (are you on vacation?)
Any news from RKI?

**Comment by EvgeniiSkrebtcov** [comment]
Hello @Tho-Mat ,

So far we do not have a request to deliver this as a hotfix. Therefore, this is a topic for one of the upcoming releases.

**Comment by Tho-Mat** [comment]
@EvgeniiSkrebtcov 
Thanks for the info last month.
Is there any news now.
Maybe the issues should be left open until a decision is made or it's implemented.
