### ISSUE TITLE
Federation server source code

### ISSUE THREAD

**Issue by maxneuvians** [corona-warn-app/cwa-server#769]
## Your Question
* Question: Hello - based on your PR #767 and the announcement by the EU (https://ec.europa.eu/commission/presscorner/detail/en/IP_20_1606) it looks like you are working on federating your keys across countries. I was unable to find source code for the federation server itself and wondered if you had a link handy? I know that T-Systems and SAP are working on it, so I figured you folks might be the best people to ask. Thank you for your time and hard work!

**Comment by hilmarf** [comment]
Hi @maxneuvians ,

Please find the sources at

https://github.com/eu-federation-gateway-service

Kind Regards 
Hilmar
