### ISSUE TITLE
Adjust Distribution Strategy 

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#80]
(on hold due to waiting for Google/Apple spec)

Adjust the current distribution strategy to the following:

Server checks hourly whether new keys need to be published.
-	If there are more than N keys available, a new Export should be created.
-	Otherwise, no file will be generated
-	N must be defined as a parameter (properties file)

The app will use the defined API to check what packages exist for each day. Those packages are not assigned to an hour anymore, but rather just “batchfiles”, e.g. bachfile 1, 2, and 3 for day X. A batch file may or may not be part of a bigger batch.

When an export is generated, it needs to know the exact start timestamp. Since this is now dependent on the creation of the previous export, we need to store this time somewhere. Since we are still using two different time intervals for triggering the export (hourly/daily), we need to store both time indicators.

**Comment by pithumke** [comment]
Linking #108 and specifically https://github.com/corona-warn-app/cwa-server/issues/108#issuecomment-631489124. Consider closing duplicate.

**Comment by christian-kirschnick** [comment]
Closing this in favor of #108 .
