### ISSUE TITLE
Check online server version

### ISSUE THREAD

**Issue by Tho-Mat** [corona-warn-app/cwa-server#847]
Is there a way to see what version of the server is online?

**Comment by EvgeniiSkrebtcov** [comment]
Hello @Tho-Mat ,

Server versions can be checked [here](https://github.com/corona-warn-app/cwa-server/releases). Online version marked with the `Latest Release` label. Currently it is 1.3.3.

At the moment we do not serve cwa backend version via the API but will consider this for the future releases.
